import {test} from 'node:test';
import assert from 'node:assert/strict';
import {enrollCadence,CadenceExists} from './cadence-enrollment.ts';
import {memoryDb} from './testing/memory-db.ts';
const input={cardId:'card',personId:'person',owner:'suuchi' as const,mode:'manual',rules:{},steps:[{step_number:1,channel:'email',kind:'review',title:'Follow up',detail:'Review',subject:'Hello',body:'Hi',status:'pending',scheduled_at:'2035-01-01'}]};
test('reenrollment preserves a sequence with historical steps',async()=>{const h=memoryDb({cadences:[{id:'c',card_id:'card',person_id:'person',owner:'suuchi',status:'active'}],cadence_steps:[{id:'s',cadence_id:'c',step_number:1,status:'sent'}]});await assert.rejects(enrollCadence(h.db,input),CadenceExists);assert.equal(h.tables.cadence_steps[0].status,'sent')});
test('concurrent enrollment creates one set of steps',async()=>{const h=memoryDb();await Promise.allSettled([enrollCadence(h.db,input),enrollCadence(h.db,input)]);assert.equal(h.tables.cadences.length,1);assert.equal(h.tables.cadence_steps.length,1);assert.equal(h.tables.cadences[0].status,'active')});
test('failed child write remains inactive and retry resumes saved payload',async()=>{const h=memoryDb();h.fail('cadence_steps','insert');await assert.rejects(enrollCadence(h.db,input),/incomplete/);assert.equal(h.tables.cadences[0].status,'draft');await enrollCadence(h.db,{...input,steps:[{...input.steps[0],body:'Changed retry'}]});assert.equal(h.tables.cadence_steps[0].body,'Hi');assert.equal(h.tables.cadences[0].status,'active')});
test('legacy empty active parent is repairable',async()=>{const h=memoryDb({cadences:[{id:'c',card_id:'card',person_id:'person',owner:'suuchi',status:'active',updated_at:'r',rules:{}}]});await enrollCadence(h.db,input);assert.equal(h.tables.cadence_steps.length,1)});
