import { decrypt } from "./crypto.ts";import { admin } from "./supabase/admin.ts";import type { Owner } from "./types.ts";
// Trim every value: credentials pasted into a dashboard often carry a stray newline or space,
// which Google rejects as invalid_client / redirect_uri_mismatch. Never send that whitespace.
function config(){return {client_id:(process.env.GOOGLE_CLIENT_ID??"").trim(),client_secret:(process.env.GOOGLE_CLIENT_SECRET??"").trim(),redirect_uri:(process.env.GOOGLE_REDIRECT_URI??"").trim()}}
// Send + read replies (for cadence) and full Calendar (free/busy + create invites for "Propose times"); userinfo.email captures the real connected address.
export const GOOGLE_SCOPES="openid email https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/calendar";
export function oauthUrl(owner:Owner){const {client_id,redirect_uri}=config();const q=new URLSearchParams({client_id,redirect_uri,response_type:"code",scope:GOOGLE_SCOPES,access_type:"offline",prompt:"select_account consent",include_granted_scopes:"true",state:owner});return `https://accounts.google.com/o/oauth2/v2/auth?${q}`}
export async function exchangeCode(code:string){const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({...config(),code,grant_type:"authorization_code"})});if(!response.ok)throw new Error("Google OAuth exchange failed");return response.json() as Promise<{access_token:string;refresh_token:string;scope:string}>}
// The email address of the account that just authorized, so we store the real sender rather than a guessed one.
export async function googleEmail(accessToken:string){const response=await fetch("https://openidconnect.googleapis.com/v1/userinfo",{headers:{authorization:`Bearer ${accessToken}`}});if(!response.ok)return null;return (await response.json() as {email?:string}).email??null}
async function accessToken(owner:Owner){const {data}=await admin().from("gmail_connections").select("refresh_token_ciphertext").eq("owner",owner).single();if(!data)throw new Error(`Gmail is not connected for ${owner}`);const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({...config(),refresh_token:decrypt(data.refresh_token_ciphertext),grant_type:"refresh_token"})});if(!response.ok)throw new Error("Unable to refresh Gmail access");return (await response.json() as {access_token:string}).access_token}
// Exposed so the calendar helpers can call Google APIs with the same refreshed token.
export async function ownerAccessToken(owner:Owner){return accessToken(owner)}
const base64url=(s:string)=>Buffer.from(s).toString("base64url");
export async function sendEmail(owner:Owner,from:string,to:string,subject:string,body:string,threadId?:string,cc?:string[],html?:string){const token=await accessToken(owner);const head=[`From: ${from}`,`To: ${to}`];if(cc&&cc.length)head.push(`Cc: ${cc.join(", ")}`);head.push(`Subject: ${subject}`,"MIME-Version: 1.0");let mime:string;if(html){const boundary=`nw_${Date.now().toString(36)}`;head.push(`Content-Type: multipart/alternative; boundary="${boundary}"`);mime=[head.join("\r\n"),"",`--${boundary}`,"Content-Type: text/plain; charset=UTF-8","",body,`--${boundary}`,"Content-Type: text/html; charset=UTF-8","",html,`--${boundary}--`,""].join("\r\n")}else{head.push("Content-Type: text/plain; charset=UTF-8");mime=[head.join("\r\n"),"",body].join("\r\n")}const raw=base64url(mime);const response=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/send",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({raw,threadId})});if(!response.ok)throw new Error(`Gmail send failed: ${response.status}`);return response.json() as Promise<{id:string;threadId:string}>}
export async function thread(owner:Owner,id:string){const token=await accessToken(owner);const response=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/threads/${id}?format=full`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(`Gmail thread read failed: ${response.status}`);return response.json() as Promise<{messages:Array<{id:string;internalDate:string;payload:{headers:Array<{name:string;value:string}>;body?:{data?:string};parts?:Array<{mimeType:string;body:{data?:string}}>}}>}>}
