// Generated from data/Nine67_Outbound_Targets_Cut.csv. Run npm run targets:generate after replacing the workbook.

export type TargetTier = "A1" | "A2" | "B" | "C" | "removed";

export const targetTierData: ReadonlyArray<readonly [website: string, tier: TargetTier, dropReason: string]> = [
  ["aprio.com","A1",""],
  ["armanino.com","A1",""],
  ["ascendtogether.com","A1",""],
  ["criadv.com","A1",""],
  ["cbh.com","A1",""],
  ["citrincooperman.com","A1",""],
  ["eidebailly.com","A1",""],
  ["pkfod.com","A1",""],
  ["wipfli.com","A1",""],
  ["cretepa.com","A1",""],
  ["sikich.com","A1",""],
  ["uhy-us.com","A1",""],
  ["cohenco.com","A1",""],
  ["doeren.com","A1",""],
  ["elliottdavis.com","A1",""],
  ["frazierdeeter.com","A1",""],
  ["platformag.com","A1",""],
  ["richeymay.com","A1",""],
  ["saxllp.com","A1",""],
  ["schellman.com","A1",""],
  ["smith-howard.com","A1",""],
  ["sorren.com","A1",""],
  ["springlineadvisory.com","A1",""],
  ["archerlewis.com","A1",""],
  ["conseroglobal.com","A1",""],
  ["lmcas.com","A1",""],
  ["lhmc.com","A1",""],
  ["nicholscauley.com","A1",""],
  ["prosperitypartners.com","A1",""],
  ["achieve.com","A1",""],
  ["crossriver.com","A1",""],
  ["bestegg.com","A1",""],
  ["carsongroup.com","A1",""],
  ["kiavi.com","A1",""],
  ["analysisgroup.com","A1",""],
  ["ankura.com","A1",""],
  ["thinkbrg.com","A1",""],
  ["crai.com","A1",""],
  ["credera.com","A1",""],
  ["exponent.com","A1",""],
  ["lek.com","A1",""],
  ["nordicglobal.com","A1",""],
  ["rgp.com","A1",""],
  ["tegria.com","A1",""],
  ["accordion.com","A1",""],
  ["argano.com","A1",""],
  ["blend360.com","A1",""],
  ["cfgi.com","A1",""],
  ["cornerstone.com","A1",""],
  ["daugherty.com","A1",""],
  ["forrester.com","A1",""],
  ["fractal.ai","A1",""],
  ["northhighland.com","A1",""],
  ["pointb.com","A1",""],
  ["quantiphi.com","A1",""],
  ["simon-kucher.com","A1",""],
  ["chartis.com","A1",""],
  ["thehackettgroup.com","A1",""],
  ["tredence.com","A1",""],
  ["10pearls.com","A1",""],
  ["aarete.com","A1",""],
  ["e78partners.com","A1",""],
  ["embarkwithus.com","A1",""],
  ["exiger.com","A1",""],
  ["infotech.com","A1",""],
  ["isg-one.com","A1",""],
  ["kaufmanhall.com","A1",""],
  ["riveron.com","A1",""],
  ["solomonedwards.com","A1",""],
  ["spauldingridge.com","A1",""],
  ["trinitylifesciences.com","A1",""],
  ["csgdelivers.com","A1",""],
  ["clarkstonconsulting.com","A1",""],
  ["clearsulting.com","A1",""],
  ["stax.com","A1",""],
  ["bounteous.com","A1",""],
  ["compucom.com","A1",""],
  ["encora.com","A1",""],
  ["ensono.com","A1",""],
  ["flexential.com","A1",""],
  ["levelblue.com","A1",""],
  ["lyratechnologygroup.com","A1",""],
  ["perficient.com","A1",""],
  ["redriver.com","A1",""],
  ["tierpoint.com","A1",""],
  ["vaco.com","A1",""],
  ["westmonroe.com","A1",""],
  ["apexon.com","A1",""],
  ["bluemantis.com","A1",""],
  ["coalfire.com","A1",""],
  ["cyderes.com","A1",""],
  ["eliassen.com","A1",""],
  ["integrisit.com","A1",""],
  ["marconet.com","A1",""],
  ["milestone.tech","A1",""],
  ["ness.com","A1",""],
  ["reliaquest.com","A1",""],
  ["tpx.com","A1",""],
  ["thrivenextgen.com","A1",""],
  ["bluevoyant.com","A1",""],
  ["dataprise.com","A1",""],
  ["datavail.com","A1",""],
  ["deepwatch.com","A1",""],
  ["expedient.com","A1",""],
  ["improving.com","A1",""],
  ["logically.com","A1",""],
  ["magna5.com","A1",""],
  ["meriplex.com","A1",""],
  ["netrixglobal.com","A1",""],
  ["newchartertech.com","A1",""],
  ["nexustek.com","A1",""],
  ["ntirety.com","A1",""],
  ["ntiva.com","A1",""],
  ["onixnet.com","A1",""],
  ["resultant.com","A1",""],
  ["vc3.com","A1",""],
  ["esentire.com","A1",""],
  ["coretelligent.com","A1",""],
  ["corsicatech.com","A1",""],
  ["criticalstart.com","A1",""],
  ["dyopath.com","A1",""],
  ["involta.com","A1",""],
  ["otava.com","A1",""],
  ["sourcepass.com","A1",""],
  ["legalshield.com","A1",""],
  ["unitedlex.com","A1",""],
  ["axiomlaw.com","A1",""],
  ["harborglobal.com","A1",""],
  ["litera.com","A1",""],
  ["relativity.com","A1",""],
  ["veritext.com","A1",""],
  ["imanage.com","A1",""],
  ["haystackid.com","A1",""],
  ["integreon.com","A1",""],
  ["lighthouseglobal.com","A1",""],
  ["netdocuments.com","A1",""],
  ["rafilawgroup.com","A1",""],
  ["dudleydebosier.com","A1",""],
  ["lufkin.com","A1",""],
  ["deptagency.com","A1",""],
  ["inmar.com","A1",""],
  ["realchemistry.com","A1",""],
  ["valtech.com","A1",""],
  ["data-axle.com","A1",""],
  ["eversanaintouch.com","A1",""],
  ["tinuiti.com","A1",""],
  ["ansira.com","A1",""],
  ["brainlabsdigital.com","A1",""],
  ["rga.com","A1",""],
  ["wpromote.com","A1",""],
  ["powerdigitalmarketing.com","A1",""],
  ["cornerstoneondemand.com","A1",""],
  ["diligent.com","A1",""],
  ["finthrive.com","A1",""],
  ["fortra.com","A1",""],
  ["hyland.com","A1",""],
  ["neweratech.com","A1",""],
  ["pingidentity.com","A1",""],
  ["precisely.com","A1",""],
  ["quest.com","A1",""],
  ["transportationinsight.com","A1",""],
  ["trucordia.com","A1",""],
  ["3cloudsolutions.com","A1",""],
  ["beyondtrust.com","A1",""],
  ["clarience.com","A1",""],
  ["gsmoutdoors.com","A1",""],
  ["jensenhughes.com","A1",""],
  ["mrisoftware.com","A1",""],
  ["mediaocean.com","A1",""],
  ["modmed.com","A1",""],
  ["montway.com","A1",""],
  ["signanthealth.com","A1",""],
  ["smartcaresolutions.com","A1",""],
  ["symplr.com","A1",""],
  ["usertesting.com","A1",""],
  ["worldwide.com","A1",""],
  ["buildertrend.com","A1",""],
  ["caylent.com","A1",""],
  ["decopac.com","A1",""],
  ["denodo.com","A1",""],
  ["elevatepfs.com","A1",""],
  ["everservice.com","A1",""],
  ["eci.com","A1",""],
  ["hugeinc.com","A1",""],
  ["sonatype.com","A1",""],
  ["valenzhealth.com","A1",""],
  ["phdata.io","A1",""],
  ["bluesight.com","A1",""],
  ["cuestapartners.com","A1",""],
  ["docupace.com","A1",""],
  ["fusionrm.com","A1",""],
  ["hueman.com","A1",""],
  ["ncontracts.com","A1",""],
  ["trinamix.com","A1",""],
  ["mbakerintl.com","A1",""],
  ["pacelabs.com","A1",""],
  ["taskus.com","A1",""],
  ["teamues.com","A1",""],
  ["woolpert.com","A1",""],
  ["ardurra.com","A1",""],
  ["businessolver.com","A1",""],
  ["cielotalent.com","A1",""],
  ["entrustsol.com","A1",""],
  ["startek.com","A1",""],
  ["trinityconsultants.com","A1",""],
  ["accurategroup.com","A1",""],
  ["classvaluation.com","A1",""],
  ["1800contacts.com","A1",""],
  ["backcountry.com","A1",""],
  ["chwinery.com","A1",""],
  ["hungryroot.com","A1",""],
  ["purposebrands.com","A1",""],
  ["functionofbeauty.com","A1",""],
  ["hannaandersson.com","A1",""],
  ["tonal.com","A1",""],
  ["anaplan.com","A1",""],
  ["appliedsystems.com","A1",""],
  ["aptean.com","A1",""],
  ["availity.com","A1",""],
  ["avalara.com","A1",""],
  ["bottomline.com","A1",""],
  ["cision.com","A1",""],
  ["connectwise.com","A1",""],
  ["coupa.com","A1",""],
  ["eab.com","A1",""],
  ["ecisolutions.com","A1",""],
  ["ellucian.com","A1",""],
  ["inovalon.com","A1",""],
  ["instructure.com","A1",""],
  ["integralads.com","A1",""],
  ["jamf.com","A1",""],
  ["medallia.com","A1",""],
  ["merative.com","A1",""],
  ["ntst.com","A1",""],
  ["nextgen.com","A1",""],
  ["powerschool.com","A1",""],
  ["sovos.com","A1",""],
  ["verint.com","A1",""],
  ["wellsky.com","A1",""],
  ["isolvedhcm.com","A1",""],
  ["acquia.com","A1",""],
  ["avidxchange.com","A1",""],
  ["bazaarvoice.com","A1",""],
  ["boomi.com","A1",""],
  ["bullhorn.com","A1",""],
  ["centralsquare.com","A1",""],
  ["constantcontact.com","A1",""],
  ["duckcreek.com","A1",""],
  ["emburse.com","A1",""],
  ["everbridge.com","A1",""],
  ["granicus.com","A1",""],
  ["greenwayhealth.com","A1",""],
  ["meridianlink.com","A1",""],
  ["mindbodyonline.com","A1",""],
  ["olo.com","A1",""],
  ["optimizely.com","A1",""],
  ["pros.com","A1",""],
  ["planview.com","A1",""],
  ["pluralsight.com","A1",""],
  ["renaissance.com","A1",""],
  ["sitecore.com","A1",""],
  ["surveymonkey.com","A1",""],
  ["tricentis.com","A1",""],
  ["zuora.com","A1",""],
  ["zywave.com","A1",""],
  ["icims.com","A1",""],
  ["abrigo.com","A1",""],
  ["accela.com","A1",""],
  ["acumatica.com","A1",""],
  ["allvuesystems.com","A1",""],
  ["birdeye.com","A1",""],
  ["bonterratech.com","A1",""],
  ["cority.com","A1",""],
  ["experityhealth.com","A1",""],
  ["gainsight.com","A1",""],
  ["greenhouse.com","A1",""],
  ["jaggaer.com","A1",""],
  ["kyruushealth.com","A1",""],
  ["logicmonitor.com","A1",""],
  ["nintex.com","A1",""],
  ["payscale.com","A1",""],
  ["quickbase.com","A1",""],
  ["salesloft.com","A1",""],
  ["unanet.com","A1",""],
  ["ehs.com","A1",""],
  ["vendavo.com","A1",""],
  ["workwave.com","A1",""],
  ["wrike.com","A1",""],
  ["xactly.com","A1",""],
  ["bswift.com","A1",""],
  ["cendyn.com","A1",""],
  ["mybluegrace.com","A1",""],
  ["lazerlogistics.com","A1",""],
  ["plslogistics.com","A1",""],
  ["andersen.com","A2",""],
  ["withum.com","A2",""],
  ["bpm.com","A2",""],
  ["kearneyco.com","A2",""],
  ["btcpa.net","A2",""],
  ["berrydunn.com","A2",""],
  ["cshco.com","A2",""],
  ["frankrimerman.com","A2",""],
  ["hco.com","A2",""],
  ["ksmcpa.com","A2",""],
  ["kaufmanrossin.com","A2",""],
  ["lbmc.com","A2",""],
  ["mgocpa.com","A2",""],
  ["pragermetis.com","A2",""],
  ["rklcpa.com","A2",""],
  ["schgroup.com","A2",""],
  ["schneiderdowns.com","A2",""],
  ["warrenaverett.com","A2",""],
  ["anderscpa.com","A2",""],
  ["auxis.com","A2",""],
  ["centriconsulting.com","A2",""],
  ["deandorton.com","A2",""],
  ["gtmtax.com","A2",""],
  ["hogantaylor.com","A2",""],
  ["lutz.us","A2",""],
  ["pyapc.com","A2",""],
  ["redw.com","A2",""],
  ["sensiba.com","A2",""],
  ["wolfandco.com","A2",""],
  ["alliantcreditunion.org","A2",""],
  ["customersbank.com","A2",""],
  ["dcu.org","A2",""],
  ["donegalgroup.com","A2",""],
  ["employers.com","A2",""],
  ["firsttechfed.com","A2",""],
  ["hcigroup.com","A2",""],
  ["lemonade.com","A2",""],
  ["navient.com","A2",""],
  ["oportun.com","A2",""],
  ["pagaya.com","A2",""],
  ["plmr.com","A2",""],
  ["paymentus.com","A2",""],
  ["regionalmanagement.com","A2",""],
  ["seacoastbank.com","A2",""],
  ["thebancorp.com","A2",""],
  ["upstart.com","A2",""],
  ["vystarcu.org","A2",""],
  ["wafdbank.com","A2",""],
  ["bowheadspecialty.com","A2",""],
  ["cardinalfinancial.com","A2",""],
  ["coastalbank.com","A2",""],
  ["dave.com","A2",""],
  ["liveoakbank.com","A2",""],
  ["msufcu.org","A2",""],
  ["origin.bank","A2",""],
  ["patelco.org","A2",""],
  ["tfin.com","A2",""],
  ["better.com","A2",""],
  ["openlending.com","A2",""],
  ["turn14.com","A2",""],
  ["wurthindustry.com","A2",""],
  ["bossard.com","A2",""],
  ["checkers.com","A2",""],
  ["deltaco.com","A2",""],
  ["blackbox.com","A2",""],
  ["collabera.com","A2",""],
  ["fulcrumitpartners.com","A2",""],
  ["gdt.com","A2",""],
  ["ironbow.com","A2",""],
  ["us.logicalis.com","A2",""],
  ["mainline.com","A2",""],
  ["thundercattech.com","A2",""],
  ["ctg.com","A2",""],
  ["denaliai.com","A2",""],
  ["genesis10.com","A2",""],
  ["griddynamics.com","A2",""],
  ["impactmybiz.com","A2",""],
  ["myriad360.com","A2",""],
  ["sayers.com","A2",""],
  ["sentinel.com","A2",""],
  ["evolvingsol.com","A2",""],
  ["mastechdigital.com","A2",""],
  ["parivedasolutions.com","A2",""],
  ["2ndwatch.com","A2",""],
  ["launchconsulting.com","A2",""],
  ["logic2020.com","A2",""],
  ["akerman.com","A2",""],
  ["bakerbotts.com","A2",""],
  ["bakerdonelson.com","A2",""],
  ["ballardspahr.com","A2",""],
  ["btlaw.com","A2",""],
  ["dwt.com","A2",""],
  ["fenwick.com","A2",""],
  ["fr.com","A2",""],
  ["foxrothschild.com","A2",""],
  ["grsm.com","A2",""],
  ["gunder.com","A2",""],
  ["haynesboone.com","A2",""],
  ["huschblackwell.com","A2",""],
  ["intapp.com","A2",""],
  ["jacksonlewis.com","A2",""],
  ["legalzoom.com","A2",""],
  ["littler.com","A2",""],
  ["lowenstein.com","A2",""],
  ["manatt.com","A2",""],
  ["ogletree.com","A2",""],
  ["shb.com","A2",""],
  ["taftlaw.com","A2",""],
  ["womblebonddickinson.com","A2",""],
  ["beneschlaw.com","A2",""],
  ["csklegal.com","A2",""],
  ["fticonsulting.com","A2",""],
  ["fisherphillips.com","A2",""],
  ["honigman.com","A2",""],
  ["kldiscovery.com","A2",""],
  ["quarles.com","A2",""],
  ["spencerfane.com","A2",""],
  ["thompsonhine.com","A2",""],
  ["transperfectlegal.com","A2",""],
  ["vorys.com","A2",""],
  ["wiley.law","A2",""],
  ["wilsonelser.com","A2",""],
  ["chapman.com","A2",""],
  ["elevate.law","A2",""],
  ["factor.law","A2",""],
  ["fennemorelaw.com","A2",""],
  ["goldbergsegalla.com","A2",""],
  ["michaelbest.com","A2",""],
  ["offitkurman.com","A2",""],
  ["mecinc.com","A2",""],
  ["roush.com","A2",""],
  ["shure.com","A2",""],
  ["sugarcreek.com","A2",""],
  ["gwelectric.com","A2",""],
  ["edelman.com","A2",""],
  ["horizonmedia.com","A2",""],
  ["klick.com","A2",""],
  ["wearemoore.com","A2",""],
  ["thebrandtechgroup.com","A2",""],
  ["webershandwick.com","A2",""],
  ["amsive.com","A2",""],
  ["assemblyglobal.com","A2",""],
  ["basis.com","A2",""],
  ["jellyfish.com","A2",""],
  ["vaynermedia.com","A2",""],
  ["apcoworldwide.com","A2",""],
  ["adswerve.com","A2",""],
  ["codeandtheory.com","A2",""],
  ["gale.agency","A2",""],
  ["goodwaygroup.com","A2",""],
  ["hartehanks.com","A2",""],
  ["keplergrp.com","A2",""],
  ["known.is","A2",""],
  ["modop.com","A2",""],
  ["pmg.com","A2",""],
  ["rightpoint.com","A2",""],
  ["ruderfinn.com","A2",""],
  ["empowermm.com","A2",""],
  ["hunterpr.com","A2",""],
  ["newengen.com","A2",""],
  ["ovative.com","A2",""],
  ["saiddifferently.com","A2",""],
  ["terakeet.com","A2",""],
  ["tombras.com","A2",""],
  ["translation.com","A2",""],
  ["wongdoody.com","A2",""],
  ["associaonline.com","A2",""],
  ["atriumworks.com","A2",""],
  ["berkadia.com","A2",""],
  ["brownandcaldwell.com","A2",""],
  ["dewberry.com","A2",""],
  ["ibex.co","A2",""],
  ["imacorp.com","A2",""],
  ["judge.com","A2",""],
  ["marcusmillichap.com","A2",""],
  ["montrose-env.com","A2",""],
  ["salasobrien.com","A2",""],
  ["willdan.com","A2",""],
  ["altusgroup.com","A2",""],
  ["bowman.com","A2",""],
  ["hksinc.com","A2",""],
  ["scsengineers.com","A2",""],
  ["thorntontomasetti.com","A2",""],
  ["clearcapital.com","A2",""],
  ["newfront.com","A2",""],
  ["walterpmoore.com","A2",""],
  ["cititrends.com","A2",""],
  ["duluthtrading.com","A2",""],
  ["ethanallen.com","A2",""],
  ["wearfigs.com","A2",""],
  ["fabletics.com","A2",""],
  ["jjill.com","A2",""],
  ["mistercarwash.com","A2",""],
  ["skims.com","A2",""],
  ["lovesac.com","A2",""],
  ["therealreal.com","A2",""],
  ["thrivemarket.com","A2",""],
  ["traeger.com","A2",""],
  ["warbyparker.com","A2",""],
  ["aka-brands.com","A2",""],
  ["bombas.com","A2",""],
  ["brilliantearth.com","A2",""],
  ["buildabear.com","A2",""],
  ["dxl.com","A2",""],
  ["greatclips.com","A2",""],
  ["ro.co","A2",""],
  ["stockx.com","A2",""],
  ["tecovas.com","A2",""],
  ["therabody.com","A2",""],
  ["thredup.com","A2",""],
  ["verabradley.com","A2",""],
  ["xponential.com","A2",""],
  ["zenni.com","A2",""],
  ["ridge.com","A2",""],
  ["alarm.com","A2",""],
  ["appfolio.com","A2",""],
  ["appian.com","A2",""],
  ["blackline.com","A2",""],
  ["braze.com","A2",""],
  ["clearwateranalytics.com","A2",""],
  ["deltek.com","A2",""],
  ["descartes.com","A2",""],
  ["doubleverify.com","A2",""],
  ["doximity.com","A2",""],
  ["kinaxis.com","A2",""],
  ["navan.com","A2",""],
  ["pointclickcare.com","A2",""],
  ["q2.com","A2",""],
  ["rippling.com","A2",""],
  ["spscommerce.com","A2",""],
  ["servicetitan.com","A2",""],
  ["sprinklr.com","A2",""],
  ["vertexinc.com","A2",""],
  ["workiva.com","A2",""],
  ["eclinicalworks.com","A2",""],
  ["ncino.com","A2",""],
  ["agilysys.com","A2",""],
  ["alkami.com","A2",""],
  ["amplitude.com","A2",""],
  ["attentive.com","A2",""],
  ["calendly.com","A2",""],
  ["domo.com","A2",""],
  ["entrata.com","A2",""],
  ["gong.io","A2",""],
  ["healthcatalyst.com","A2",""],
  ["gomotive.com","A2",""],
  ["n-able.com","A2",""],
  ["outreach.io","A2",""],
  ["phreesia.com","A2",""],
  ["powerfleet.com","A2",""],
  ["seismic.com","A2",""],
  ["sproutsocial.com","A2",""],
  ["yext.com","A2",""],
  ["zapier.com","A2",""],
  ["o9solutions.com","A2",""],
  ["6sense.com","A2",""],
  ["activecampaign.com","A2",""],
  ["arcadia.io","A2",""],
  ["blend.com","A2",""],
  ["centralreach.com","A2",""],
  ["clari.com","A2",""],
  ["companycam.com","A2",""],
  ["definitivehc.com","A2",""],
  ["eightfold.ai","A2",""],
  ["fourkites.com","A2",""],
  ["highspot.com","A2",""],
  ["housecallpro.com","A2",""],
  ["innovaccer.com","A2",""],
  ["iterable.com","A2",""],
  ["ivalua.com","A2",""],
  ["getjobber.com","A2",""],
  ["lattice.com","A2",""],
  ["opengov.com","A2",""],
  ["phenom.com","A2",""],
  ["podium.com","A2",""],
  ["restaurant365.com","A2",""],
  ["tebra.com","A2",""],
  ["uplandsoftware.com","A2",""],
  ["getweave.com","A2",""],
  ["project44.com","A2",""],
  ["taservices.com","A2",""],
  ["transervice.com","A2",""],
  ["hcvt.com","B",""],
  ["weaver.com","B",""],
  ["anchin.com","B",""],
  ["blueandco.com","B",""],
  ["grassiadvisors.com","B",""],
  ["hbkcpa.com","B",""],
  ["mjcpa.com","B",""],
  ["millercooper.com","B",""],
  ["novoco.com","B",""],
  ["pinionglobal.com","B",""],
  ["rehmann.com","B",""],
  ["rubinbrown.com","B",""],
  ["singerlewak.com","B",""],
  ["bonadio.com","B",""],
  ["whitleypenn.com","B",""],
  ["aafcpa.com","B",""],
  ["adamsbrowncpa.com","B",""],
  ["aldrichadvisors.com","B",""],
  ["bmss.com","B",""],
  ["bnncpa.com","B",""],
  ["boulaygroup.com","B",""],
  ["bradymartz.com","B",""],
  ["becpas.com","B",""],
  ["cainwatters.com","B",""],
  ["clarknuber.com","B",""],
  ["gbq.com","B",""],
  ["ghjadvisors.com","B",""],
  ["grfcpa.com","B",""],
  ["gursey.com","B",""],
  ["hhmcpas.com","B",""],
  ["hayniecpas.com","B",""],
  ["honkamp.com","B",""],
  ["johnsonlambert.com","B",""],
  ["kahnlitwin.com","B",""],
  ["kempercpa.com","B",""],
  ["kmco.com","B",""],
  ["meadenmoore.com","B",""],
  ["millerkaplan.com","B",""],
  ["pbmares.com","B",""],
  ["reacpa.com","B",""],
  ["tannerco.com","B",""],
  ["windes.com","B",""],
  ["wiss.com","B",""],
  ["yhbcpa.com","B",""],
  ["americafirst.com","B",""],
  ["bancofcal.com","B",""],
  ["boh.com","B",""],
  ["bannerbank.com","B",""],
  ["captrust.com","B",""],
  ["cmgfi.com","B",""],
  ["cathaybank.com","B",""],
  ["centralbancompany.com","B",""],
  ["corient.com","B",""],
  ["creativeplanning.com","B",""],
  ["easternbank.com","B",""],
  ["enterprisebank.com","B",""],
  ["exeterfinance.com","B",""],
  ["fairwayindependentmc.com","B",""],
  ["busey.com","B",""],
  ["ffin.com","B",""],
  ["fhb.com","B",""],
  ["firstinterstatebank.com","B",""],
  ["firstpremier.com","B",""],
  ["fourleaffcu.org","B",""],
  ["glacierbancorp.com","B",""],
  ["globalcu.org","B",""],
  ["golden1.com","B",""],
  ["greensky.com","B",""],
  ["guildmortgage.com","B",""],
  ["hightoweradvisors.com","B",""],
  ["homebancshares.com","B",""],
  ["iccu.com","B",""],
  ["rocklandtrust.com","B",""],
  ["ibc.com","B",""],
  ["kestrafinancial.com","B",""],
  ["lmcu.org","B",""],
  ["marinerwealthadvisors.com","B",""],
  ["marinerfinance.com","B",""],
  ["marqeta.com","B",""],
  ["mechanicsbank.com","B",""],
  ["movement.com","B",""],
  ["newamericanfunding.com","B",""],
  ["north.com","B",""],
  ["pathward.com","B",""],
  ["payoneer.com","B",""],
  ["prioritycommerce.com","B",""],
  ["provident.bank","B",""],
  ["rbfcu.org","B",""],
  ["renasant.com","B",""],
  ["rockco.com","B",""],
  ["ssfcu.org","B",""],
  ["servisfirstbank.com","B",""],
  ["simmonsbank.com","B",""],
  ["suncoastcreditunion.com","B",""],
  ["townebank.com","B",""],
  ["trustmark.com","B",""],
  ["wealthenhancement.com","B",""],
  ["wesbanco.com","B",""],
  ["worldacceptance.com","B",""],
  ["amerisafe.com","B",""],
  ["anb.com","B",""],
  ["asbhawaii.com","B",""],
  ["bankplus.net","B",""],
  ["b1bank.com","B",""],
  ["centier.com","B",""],
  ["deltacommunitycu.com","B",""],
  ["dollar.bank","B",""],
  ["flywire.com","B",""],
  ["lendmarkfinancial.com","B",""],
  ["merceradvisors.com","B",""],
  ["nicoletbank.com","B",""],
  ["onpointcu.com","B",""],
  ["payroc.com","B",""],
  ["peoplesbancorp.com","B",""],
  ["planethomelending.com","B",""],
  ["repay.com","B",""],
  ["sezzle.com","B",""],
  ["southside.com","B",""],
  ["syb.com","B",""],
  ["allworthfinancial.com","B",""],
  ["beaconpointe.com","B",""],
  ["ccbg.com","B",""],
  ["celerocommerce.com","B",""],
  ["civista.bank","B",""],
  ["dacotahbank.com","B",""],
  ["epwealth.com","B",""],
  ["fnbalaska.com","B",""],
  ["fortispay.com","B",""],
  ["htb.com","B",""],
  ["mai.capital","B",""],
  ["prmg.net","B",""],
  ["peapackprivate.com","B",""],
  ["savantwealth.com","B",""],
  ["usamortgage.com","B",""],
  ["vantage.bank","B",""],
  ["washtrust.com","B",""],
  ["i3verticals.com","B",""],
  ["gallup.com","B",""],
  ["nera.com","B",""],
  ["publicconsultinggroup.com","B",""],
  ["secretariat-intl.com","B",""],
  ["segalco.com","B",""],
  ["stout.com","B",""],
  ["1898andco.com","B",""],
  ["bateswhite.com","B",""],
  ["consertus.com","B",""],
  ["ecgmc.com","B",""],
  ["guidepostsolutions.com","B",""],
  ["mu-sigma.com","B",""],
  ["optimumhit.com","B",""],
  ["prophet.com","B",""],
  ["stoneturn.com","B",""],
  ["brattle.com","B",""],
  ["alexandergroup.com","B",""],
  ["appliedvaluegroup.com","B",""],
  ["divurgent.com","B",""],
  ["duckercarlisle.com","B",""],
  ["scottmadden.com","B",""],
  ["senderoconsulting.com","B",""],
  ["treliant.com","B",""],
  ["afcind.com","B",""],
  ["andrewsdistributing.com","B",""],
  ["autowares.com","B",""],
  ["bdiexpress.com","B",""],
  ["bhid.com","B",""],
  ["concordancehealthcare.com","B",""],
  ["consolidatedpipe.com","B",""],
  ["consolidatedsupply.com","B",""],
  ["crescentcrown.com","B",""],
  ["dealerselectrical.com","B",""],
  ["ewie.com","B",""],
  ["famous-supply.com","B",""],
  ["ferrarofoods.com","B",""],
  ["fisherautoparts.com","B",""],
  ["gresco.com","B",""],
  ["gulfeaglesupply.com","B",""],
  ["harborwholesale.com","B",""],
  ["harcros.com","B",""],
  ["hawkinsinc.com","B",""],
  ["heilind.com","B",""],
  ["hensley.com","B",""],
  ["kendallelectric.com","B",""],
  ["kimballmidwest.com","B",""],
  ["kirbyrisk.com","B",""],
  ["sheehanfamilycompanies.com","B",""],
  ["manhattanbeer.com","B",""],
  ["merchantsfoodservice.com","B",""],
  ["meyerdistributing.com","B",""],
  ["midwestvet.net","B",""],
  ["munchsupply.com","B",""],
  ["nicholasandco.com","B",""],
  ["optimas.com","B",""],
  ["remichel.com","B",""],
  ["rshughes.com","B",""],
  ["richards-supply.com","B",""],
  ["sarnova.com","B",""],
  ["silvereagle.com","B",""],
  ["stateelectric.com","B",""],
  ["truckpro.com","B",""],
  ["turtle.com","B",""],
  ["vanmeterinc.com","B",""],
  ["coburns.com","B",""],
  ["darbydental.com","B",""],
  ["endries.com","B",""],
  ["firstsupply.com","B",""],
  ["inlineelectric.com","B",""],
  ["lockesupply.com","B",""],
  ["magidglove.com","B",""],
  ["mallory.com","B",""],
  ["martinsupply.com","B",""],
  ["masterelectronics.com","B",""],
  ["mce-inc.com","B",""],
  ["sidharvey.com","B",""],
  ["summit.com","B",""],
  ["tencarva.com","B",""],
  ["unitedelectric.com","B",""],
  ["whatchefswant.com","B",""],
  ["cummins-wagner.com","B",""],
  ["7brew.com","B",""],
  ["avifoodsystems.com","B",""],
  ["amys.com","B",""],
  ["ascenthospitality.com","B",""],
  ["baf.com","B",""],
  ["bolthouse.com","B",""],
  ["cpk.com","B",""],
  ["churchs.com","B",""],
  ["concordhotels.com","B",""],
  ["crescenthotels.com","B",""],
  ["fogodechao.com","B",""],
  ["freddys.com","B",""],
  ["gfhotels.com","B",""],
  ["greatwolf.com","B",""],
  ["harvesthill.com","B",""],
  ["hotelequities.com","B",""],
  ["kingshawaiian.com","B",""],
  ["landofrost.com","B",""],
  ["lettuce.com","B",""],
  ["lyonsmagnus.com","B",""],
  ["nothingbundtcakes.com","B",""],
  ["pfchangs.com","B",""],
  ["polarbev.com","B",""],
  ["ruizfoods.com","B",""],
  ["spbhospitality.com","B",""],
  ["sagehospitalitygroup.com","B",""],
  ["saraleefrozenbakery.com","B",""],
  ["sauerbrands.com","B",""],
  ["scooterscoffee.com","B",""],
  ["tpghotelsandresorts.com","B",""],
  ["thompsonhospitality.com","B",""],
  ["blackbeardiner.com","B",""],
  ["blountfinefoods.com","B",""],
  ["califiafarms.com","B",""],
  ["cameronmitchell.com","B",""],
  ["chickensaladchick.com","B",""],
  ["cuisinesolutions.com","B",""],
  ["enphospitality.com","B",""],
  ["fivestarfood.com","B",""],
  ["hometownfoodcompany.com","B",""],
  ["idahoan.com","B",""],
  ["kettlecuisine.com","B",""],
  ["lakeviewfarms.com","B",""],
  ["lazydogrestaurants.com","B",""],
  ["litehousefoods.com","B",""],
  ["nellson.com","B",""],
  ["olddutchfoods.com","B",""],
  ["peteandgerrys.com","B",""],
  ["secondnaturebrands.com","B",""],
  ["slimchickens.com","B",""],
  ["talkingrain.com","B",""],
  ["duckhorn.com","B",""],
  ["torchystacos.com","B",""],
  ["turkeyhill.com","B",""],
  ["walk-ons.com","B",""],
  ["athleticbrewing.com","B",""],
  ["bernerfoods.com","B",""],
  ["bobsredmill.com","B",""],
  ["chosenfoods.com","B",""],
  ["continentalserves.com","B",""],
  ["countrypurefoods.com","B",""],
  ["health-ade.com","B",""],
  ["tryhungry.com","B",""],
  ["louisianafishfry.com","B",""],
  ["metzculinary.com","B",""],
  ["nonnis.com","B",""],
  ["oldethompson.com","B",""],
  ["philzcoffee.com","B",""],
  ["purelyelizabeth.com","B",""],
  ["shipleydonuts.com","B",""],
  ["sfellc.com","B",""],
  ["drinkspindrift.com","B",""],
  ["thenutritiongroup.biz","B",""],
  ["ushg.com","B",""],
  ["velvettaco.com","B",""],
  ["whitsons.com","B",""],
  ["owsfoods.com","B",""],
  ["alku.com","B",""],
  ["loffler.com","B",""],
  ["evolveip.net","B",""],
  ["blankrome.com","B",""],
  ["cahill.com","B",""],
  ["cozen.com","B",""],
  ["dorsey.com","B",""],
  ["duanemorris.com","B",""],
  ["jw.com","B",""],
  ["katten.com","B",""],
  ["ktslaw.com","B",""],
  ["loeb.com","B",""],
  ["bracewell.com","B",""],
  ["bradley.com","B",""],
  ["bhfs.com","B",""],
  ["buchalter.com","B",""],
  ["bipc.com","B",""],
  ["carltonfields.com","B",""],
  ["choate.com","B",""],
  ["clarkhill.com","B",""],
  ["dickinsonwright.com","B",""],
  ["dinsmore.com","B",""],
  ["dykema.com","B",""],
  ["finnegan.com","B",""],
  ["foleyhoag.com","B",""],
  ["fredlaw.com","B",""],
  ["frostbrowntodd.com","B",""],
  ["hollandhart.com","B",""],
  ["icemiller.com","B",""],
  ["irell.com","B",""],
  ["joneswalker.com","B",""],
  ["knobbe.com","B",""],
  ["kobrekim.com","B",""],
  ["kutakrock.com","B",""],
  ["lathropgpm.com","B",""],
  ["mccarter.com","B",""],
  ["mto.com","B",""],
  ["pbwt.com","B",""],
  ["robinskaplan.com","B",""],
  ["saul.com","B",""],
  ["swlaw.com","B",""],
  ["steptoe.com","B",""],
  ["stinson.com","B",""],
  ["stoel.com","B",""],
  ["susmangodfrey.com","B",""],
  ["thompsoncoburn.com","B",""],
  ["vedderprice.com","B",""],
  ["wc.com","B",""],
  ["adamsandreese.com","B",""],
  ["armstrongteasdale.com","B",""],
  ["butlersnow.com","B",""],
  ["daypitney.com","B",""],
  ["fmglaw.com","B",""],
  ["maynardnexsen.com","B",""],
  ["mvalaw.com","B",""],
  ["mmmlaw.com","B",""],
  ["munsch.com","B",""],
  ["sgrlaw.com","B",""],
  ["ubglaw.com","B",""],
  ["winstead.com","B",""],
  ["arielcorp.com","B",""],
  ["ariens.com","B",""],
  ["bluebell.com","B",""],
  ["brakebush.com","B",""],
  ["casefarms.com","B",""],
  ["charlottepipe.com","B",""],
  ["fellowes.com","B",""],
  ["gojo.com","B",""],
  ["glenraven.com","B",""],
  ["gormanrupp.com","B",""],
  ["griffithfoods.com","B",""],
  ["hsmsolutions.com","B",""],
  ["hydrite.com","B",""],
  ["ki.com","B",""],
  ["kalmbachfeeds.com","B",""],
  ["kleintools.com","B",""],
  ["knapheide.com","B",""],
  ["lbfoster.com","B",""],
  ["lacksenterprises.com","B",""],
  ["lakesidefoods.com","B",""],
  ["mastersgalleryfoods.com","B",""],
  ["mazzellacompanies.com","B",""],
  ["myersindustries.com","B",""],
  ["nyxinc.com","B",""],
  ["oatey.com","B",""],
  ["pemnet.com","B",""],
  ["poly-america.com","B",""],
  ["prestagefarms.com","B",""],
  ["pretiumpkg.com","B",""],
  ["shapecorp.com","B",""],
  ["shurtape.com","B",""],
  ["sloan.com","B",""],
  ["standardtextile.com","B",""],
  ["stoughtontrailers.com","B",""],
  ["taittowers.com","B",""],
  ["thermosafe.com","B",""],
  ["unifi.com","B",""],
  ["ampcopgh.com","B",""],
  ["bemismfg.com","B",""],
  ["bernhardt.com","B",""],
  ["brentwoodindustries.com","B",""],
  ["cascadeng.com","B",""],
  ["ennis.com","B",""],
  ["eriez.com","B",""],
  ["flexco.com","B",""],
  ["hanoverfoods.com","B",""],
  ["herrs.com","B",""],
  ["hoffmaster.com","B",""],
  ["husco.com","B",""],
  ["husseycopper.com","B",""],
  ["potatorolls.com","B",""],
  ["meyertool.com","B",""],
  ["palermospizza.com","B",""],
  ["pridgeonandclay.com","B",""],
  ["requestfoods.com","B",""],
  ["resourcelabel.com","B",""],
  ["sauder.com","B",""],
  ["stellaandchewys.com","B",""],
  ["thermodisc.com","B",""],
  ["versalift.com","B",""],
  ["verusaero.com","B",""],
  ["vitamix.com","B",""],
  ["wahlusa.com","B",""],
  ["americanleather.com","B",""],
  ["astronautics.com","B",""],
  ["bettcher.com","B",""],
  ["jiffymix.com","B",""],
  ["grobbel.com","B",""],
  ["freedmanseating.com","B",""],
  ["gradywhite.com","B",""],
  ["hatchstamping.com","B",""],
  ["inprocorp.com","B",""],
  ["intlextrusions.com","B",""],
  ["jwfindustries.com","B",""],
  ["justborn.com","B",""],
  ["kewaunee.com","B",""],
  ["michelman.com","B",""],
  ["missionpharmacal.com","B",""],
  ["mtolivepickles.com","B",""],
  ["newpig.com","B",""],
  ["pennunited.com","B",""],
  ["sellmark.net","B",""],
  ["buzzballz.com","B",""],
  ["spanglercandy.com","B",""],
  ["willburt.com","B",""],
  ["woosterbrush.com","B",""],
  ["zippo.com","B",""],
  ["caymanchem.com","B",""],
  ["channellock.com","B",""],
  ["chrysan.com","B",""],
  ["motorcitystamping.com","B",""],
  ["regalresearch.com","B",""],
  ["teamwass.com","B",""],
  ["cmimediagroup.com","B",""],
  ["czarnowski.com","B",""],
  ["gpj.com","B",""],
  ["iwco.com","B",""],
  ["inizioevoke.com","B",""],
  ["precisionaq.com","B",""],
  ["wk.com","B",""],
  ["72andsunny.com","B",""],
  ["anomaly.com","B",""],
  ["canvasworldwide.com","B",""],
  ["cheil.com","B",""],
  ["derse.com","B",""],
  ["doner.com","B",""],
  ["finnpartners.com","B",""],
  ["fingerpaint.com","B",""],
  ["goodbysilverstein.com","B",""],
  ["icrinc.com","B",""],
  ["innoceanusa.com","B",""],
  ["jackmorton.com","B",""],
  ["japsolson.com","B",""],
  ["mittera.com","B",""],
  ["momentumww.com","B",""],
  ["opusagency.com","B",""],
  ["orchestra.co","B",""],
  ["prosek.com","B",""],
  ["rpa.com","B",""],
  ["wearesparks.com","B",""],
  ["supremegroup.com","B",""],
  ["martinagency.com","B",""],
  ["zenogroup.com","B",""],
  ["zadv.com","B",""],
  ["abelsontaylor.com","B",""],
  ["allisonworldwide.com","B",""],
  ["baderrutter.com","B",""],
  ["barkleyokrp.com","B",""],
  ["collemcvoy.com","B",""],
  ["c-k.com","B",""],
  ["crossmedia.com","B",""],
  ["darwill.com","B",""],
  ["deutschla.com","B",""],
  ["herodigital.com","B",""],
  ["highwirepr.com","B",""],
  ["hotwireglobal.com","B",""],
  ["impact-xm.com","B",""],
  ["mww.com","B",""],
  ["mindgruve.com","B",""],
  ["experiencenve.com","B",""],
  ["raintga.com","B",""],
  ["sequeldm.com","B",""],
  ["spectrumscience.com","B",""],
  ["trg.agency","B",""],
  ["alkegen.com","B",""],
  ["athletico.com","B",""],
  ["azurity.com","B",""],
  ["goblusky.com","B",""],
  ["excelitas.com","B",""],
  ["freshedge.com","B",""],
  ["jsheld.com","B",""],
  ["numotion.com","B",""],
  ["otcindustrial.com","B",""],
  ["ppcflex.com","B",""],
  ["pavion.com","B",""],
  ["petsuppliesplus.com","B",""],
  ["phillipspet.com","B",""],
  ["singerindustrial.com","B",""],
  ["smilebrands.com","B",""],
  ["sonnysdirect.com","B",""],
  ["springswindowfashions.com","B",""],
  ["voyantbeauty.com","B",""],
  ["wellnesspet.com","B",""],
  ["yellowstonelandscape.com","B",""],
  ["abcfitness.com","B",""],
  ["advancedderm.com","B",""],
  ["aramsco.com","B",""],
  ["betterbeing.com","B",""],
  ["brookandwhittle.com","B",""],
  ["captainds.com","B",""],
  ["centralmoloney.com","B",""],
  ["ceritypartners.com","B",""],
  ["chemicalguys.com","B",""],
  ["colibrigroup.com","B",""],
  ["colonyhardware.com","B",""],
  ["colsongroup.com","B",""],
  ["eaglefoods.com","B",""],
  ["frontlineeducation.com","B",""],
  ["hepaco.com","B",""],
  ["heartlandvetpartners.com","B",""],
  ["ingenyx.com","B",""],
  ["idera.com","B",""],
  ["krayden.com","B",""],
  ["learnbehavioral.com","B",""],
  ["lanterdeliverysystems.com","B",""],
  ["legacyservicepartners.com","B",""],
  ["metagenics.com","B",""],
  ["modeln.com","B",""],
  ["monotype.com","B",""],
  ["ncswash.com","B",""],
  ["treatingpain.com","B",""],
  ["nationsroof.com","B",""],
  ["nellsonllc.com","B",""],
  ["nelsonglobalproducts.com","B",""],
  ["nivelparts.com","B",""],
  ["oceanshealthcare.com","B",""],
  ["oncoursehome.com","B",""],
  ["pathstone.com","B",""],
  ["performancehealth.com","B",""],
  ["qualuscorp.com","B",""],
  ["rticoutdoors.com","B",""],
  ["rimkus.com","B",""],
  ["roughcountry.com","B",""],
  ["shermco.com","B",""],
  ["stirfoods.com","B",""],
  ["teamtech.com","B",""],
  ["techmerpm.com","B",""],
  ["vessco.com","B",""],
  ["windownation.com","B",""],
  ["cabionline.com","B",""],
  ["advancingeyecare.com","B",""],
  ["beaconcom.com","B",""],
  ["commandalkon.com","B",""],
  ["dentive.com","B",""],
  ["eptura.com","B",""],
  ["gallowayus.com","B",""],
  ["greenixpc.com","B",""],
  ["greenphire.com","B",""],
  ["hasapool.com","B",""],
  ["hillercompanies.com","B",""],
  ["inovarpackaging.com","B",""],
  ["interimhealthcare.com","B",""],
  ["lwolf.com","B",""],
  ["marmicfire.com","B",""],
  ["milanicosmetics.com","B",""],
  ["myerseps.com","B",""],
  ["oakbridgeinsurance.com","B",""],
  ["pottersignal.com","B",""],
  ["produceone.com","B",""],
  ["sb10minuteoilchange.com","B",""],
  ["vipeyes.com","B",""],
  ["wrenvironmental.com","B",""],
  ["zenith-american.com","B",""],
  ["good2grow.com","B",""],
  ["acceleratelearning.com","B",""],
  ["altapestcontrol.com","B",""],
  ["h2ocarepartners.com","B",""],
  ["pointchealth.com","B",""],
  ["strongpointpartners.com","B",""],
  ["togetherwomenshealth.com","B",""],
  ["addisongroup.com","B",""],
  ["oneatlas.com","B",""],
  ["elliman.com","B",""],
  ["foundationrp.com","B",""],
  ["geosyntec.com","B",""],
  ["higginbotham.com","B",""],
  ["highstreetpartners.com","B",""],
  ["howardhanna.com","B",""],
  ["kleinfelder.com","B",""],
  ["leavitt.com","B",""],
  ["motionrecruitment.com","B",""],
  ["patriotgis.com","B",""],
  ["stvinc.com","B",""],
  ["systemone.com","B",""],
  ["hilbgroup.com","B",""],
  ["vensure.com","B",""],
  ["worldinsurance.com","B",""],
  ["chacompanies.com","B",""],
  ["holmesmurphy.com","B",""],
  ["kidder.com","B",""],
  ["medixteam.com","B",""],
  ["northmarq.com","B",""],
  ["relationinsurance.com","B",""],
  ["theplanetgroup.com","B",""],
  ["transwestern.com","B",""],
  ["verdantas.com","B",""],
  ["drinkag1.com","B",""],
  ["davidyurman.com","B",""],
  ["gabesstores.com","B",""],
  ["harrys.com","B",""],
  ["havertys.com","B",""],
  ["hottopic.com","B",""],
  ["lakeshorelearning.com","B",""],
  ["misfitsmarket.com","B",""],
  ["oceanstatejoblot.com","B",""],
  ["pdcbrands.com","B",""],
  ["stanley1913.com","B",""],
  ["roomandboard.com","B",""],
  ["catofashions.com","B",""],
  ["containerstore.com","B",""],
  ["vitacoco.com","B",""],
  ["tillys.com","B",""],
  ["trovebrands.com","B",""],
  ["vonmaur.com","B",""],
  ["windsorstore.com","B",""],
  ["zumiez.com","B",""],
  ["altardstate.com","B",""],
  ["article.com","B",""],
  ["bark.co","B",""],
  ["dickblick.com","B",""],
  ["booksamillion.com","B",""],
  ["chomps.com","B",""],
  ["drinkcirkul.com","B",""],
  ["crunch.com","B",""],
  ["eosfitness.com","B",""],
  ["ftd.com","B",""],
  ["francescas.com","B",""],
  ["kendrascott.com","B",""],
  ["kodiakcakes.com","B",""],
  ["liquiddeath.com","B",""],
  ["drinkolipop.com","B",""],
  ["olaplex.com","B",""],
  ["orvis.com","B",""],
  ["powerstop.com","B",""],
  ["purple.com","B",""],
  ["dontdrivedirty.com","B",""],
  ["rarebeauty.com","B",""],
  ["thereformation.com","B",""],
  ["renttherunway.com","B",""],
  ["ruggable.com","B",""],
  ["solobrands.com","B",""],
  ["spanx.com","B",""],
  ["kirklands.com","B",""],
  ["thelearningexperience.com","B",""],
  ["theshadestore.com","B",""],
  ["tidalwaveautospa.com","B",""],
  ["tileshop.com","B",""],
  ["vineyardvines.com","B",""],
  ["zipscarwash.com","B",""],
  ["bollandbranch.com","B",""],
  ["brooklinen.com","B",""],
  ["cotopaxi.com","B",""],
  ["waxcenter.com","B",""],
  ["evereve.com","B",""],
  ["everlane.com","B",""],
  ["fahertybrand.com","B",""],
  ["glossier.com","B",""],
  ["grove.co","B",""],
  ["hpb.com","B",""],
  ["handandstone.com","B",""],
  ["justfoodfordogs.com","B",""],
  ["kizik.com","B",""],
  ["massageenvy.com","B",""],
  ["paige.com","B",""],
  ["playabowls.com","B",""],
  ["radianceholdings.com","B",""],
  ["restore.com","B",""],
  ["rothys.com","B",""],
  ["sportclips.com","B",""],
  ["summerfridays.com","B",""],
  ["superstarcarwash.com","B",""],
  ["wellbizbrands.com","B",""],
  ["dogtopia.com","B",""],
  ["marinelayer.com","B",""],
  ["rhone.com","B",""],
  ["e2open.com","B",""],
  ["evercommerce.com","B",""],
  ["communitybrands.com","B",""],
  ["healthstream.com","B",""],
  ["quorumsoftware.com","B",""],
  ["advancedmd.com","B",""],
  ["alegeus.com","B",""],
  ["asuresoftware.com","B",""],
  ["daxko.com","B",""],
  ["fleetio.com","B",""],
  ["officeally.com","B",""],
  ["tecsys.com","B",""],
  ["togetherwork.com","B",""],
  ["aduiepyle.com","B",""],
  ["atlasworldgroup.com","B",""],
  ["cjlogisticsamerica.com","B",""],
  ["craneww.com","B",""],
  ["evanstrans.com","B",""],
  ["heartlandexpress.com","B",""],
  ["hirschbach.com","B",""],
  ["imcc.com","B",""],
  ["ielfreight.com","B",""],
  ["kllm.com","B",""],
  ["logisticdynamics.com","B",""],
  ["logisticsplus.com","B",""],
  ["marten.com","B",""],
  ["megacorplogistics.com","B",""],
  ["m-v-t.com","B",""],
  ["neovialogistics.com","B",""],
  ["odysseylogistics.com","B",""],
  ["pamtransport.com","B",""],
  ["qualitycarriers.com","B",""],
  ["quantixscs.com","B",""],
  ["rjwgroup.com","B",""],
  ["radiantdelivers.com","B",""],
  ["roadone.com","B",""],
  ["sclogistics.com","B",""],
  ["spotinc.com","B",""],
  ["steamlogistics.com","B",""],
  ["stevenstransport.com","B",""],
  ["tmctrans.com","B",""],
  ["unigroup.com","B",""],
  ["venturelogistics.com","B",""],
  ["westernexp.com","B",""],
  ["bayandbay.com","B",""],
  ["beemac.com","B",""],
  ["circledelivers.com","B",""],
  ["dylt.com","B",""],
  ["maverickusa.com","B",""],
  ["meltontruck.com","B",""],
  ["odwlogistics.com","B",""],
  ["oakh.com","B",""],
  ["pgttrucking.com","B",""],
  ["loadrpm.com","B",""],
  ["roadrunnerfreight.com","B",""],
  ["roehl.net","B",""],
  ["tcitransportation.com","B",""],
  ["wardtlc.com","B",""],
  ["duprelogistics.com","B",""],
  ["groendyke.com","B",""],
  ["gwii.com","B",""],
  ["leonardsexpress.com","B",""],
  ["papertransport.com","B",""],
  ["speedeedelivery.com","B",""],
  ["bdo.com","C",""],
  ["bakertilly.com","C",""],
  ["cbiz.com","C",""],
  ["claconnect.com","C",""],
  ["cohnreznick.com","C",""],
  ["crowe.com","C",""],
  ["eisneramper.com","C",""],
  ["forvismazars.us","C",""],
  ["grantthornton.com","C",""],
  ["rsmus.com","C",""],
  ["ryan.com","C",""],
  ["aciworldwide.com","C",""],
  ["arvest.com","C",""],
  ["associatedbank.com","C",""],
  ["atlanticus.com","C",""],
  ["axosfinancial.com","C",""],
  ["becu.org","C",""],
  ["breadfinancial.com","C",""],
  ["cnoinc.com","C",""],
  ["commercebank.com","C",""],
  ["deluxe.com","C",""],
  ["edelmanfinancialengines.com","C",""],
  ["encorecapital.com","C",""],
  ["enova.com","C",""],
  ["fnb-online.com","C",""],
  ["fultonbank.com","C",""],
  ["greendot.com","C",""],
  ["kemper.com","C",""],
  ["kinsalecapitalgroup.com","C",""],
  ["lendingclub.com","C",""],
  ["macu.com","C",""],
  ["onemainfinancial.com","C",""],
  ["pragroup.com","C",""],
  ["pennymac.com","C",""],
  ["rate.com","C",""],
  ["remitly.com","C",""],
  ["joinroot.com","C",""],
  ["selective.com","C",""],
  ["skywardinsurance.com","C",""],
  ["texascapitalbank.com","C",""],
  ["uwm.com","C",""],
  ["universalinsuranceholdings.com","C",""],
  ["wexinc.com","C",""],
  ["loandepot.com","C",""],
  ["alixpartners.com","C",""],
  ["alvarezandmarsal.com","C",""],
  ["avanade.com","C",""],
  ["guidehouse.com","C",""],
  ["huronconsultinggroup.com","C",""],
  ["icf.com","C",""],
  ["kearney.com","C",""],
  ["kornferry.com","C",""],
  ["milliman.com","C",""],
  ["oliverwyman.com","C",""],
  ["protiviti.com","C",""],
  ["publicissapient.com","C",""],
  ["synechron.com","C",""],
  ["thoughtworks.com","C",""],
  ["zs.com","C",""],
  ["applied.com","C",""],
  ["bluelinxco.com","C",""],
  ["borderstates.com","C",""],
  ["dnow.com","C",""],
  ["digikey.com","C",""],
  ["fleetpride.com","C",""],
  ["globalindustrial.com","C",""],
  ["mholland.com","C",""],
  ["mscdirect.com","C",""],
  ["hillmangroup.com","C",""],
  ["aimbridgehospitality.com","C",""],
  ["bojangles.com","C",""],
  ["ckr.com","C",""],
  ["dennys.com","C",""],
  ["flynnrg.com","C",""],
  ["goldenstatefoods.com","C",""],
  ["ahead.com","C",""],
  ["asgn.com","C",""],
  ["onec1.com","C",""],
  ["connection.com","C",""],
  ["convergetp.com","C",""],
  ["dexian.com","C",""],
  ["epam.com","C",""],
  ["evergreensg.com","C",""],
  ["kforce.com","C",""],
  ["nwn.ai","C",""],
  ["optiv.com","C",""],
  ["rackspace.com","C",""],
  ["cdwg.com","C",""],
  ["slalom.com","C",""],
  ["trace3.com","C",""],
  ["unisys.com","C",""],
  ["zayo.com","C",""],
  ["zones.com","C",""],
  ["eplus.com","C",""],
  ["consilio.com","C",""],
  ["epiqglobal.com","C",""],
  ["lewisbrisbois.com","C",""],
  ["forthepeople.com","C",""],
  ["nelsonmullins.com","C",""],
  ["polsinelli.com","C",""],
  ["azz.com","C",""],
  ["amsted.com","C",""],
  ["carhartt.com","C",""],
  ["chamberlaingroup.com","C",""],
  ["crown.com","C",""],
  ["duravant.com","C",""],
  ["kennametal.com","C",""],
  ["kontoorbrands.com","C",""],
  ["panduit.com","C",""],
  ["powellind.com","C",""],
  ["promachbuilt.com","C",""],
  ["sandc.com","C",""],
  ["swagelok.com","C",""],
  ["trin.net","C",""],
  ["utzsnacks.com","C",""],
  ["acosta.group","C",""],
  ["advantagesolutions.net","C",""],
  ["bursonglobal.com","C",""],
  ["freeman.com","C",""],
  ["quad.com","C",""],
  ["rrd.com","C",""],
  ["stagwellglobal.com","C",""],
  ["aoncology.com","C",""],
  ["crashchampions.com","C",""],
  ["guidepointsecurity.com","C",""],
  ["insightglobal.com","C",""],
  ["integritymarketing.com","C",""],
  ["leafhome.com","C",""],
  ["amnhealthcare.com","C",""],
  ["acrisure.com","C",""],
  ["alight.com","C",""],
  ["alorica.com","C",""],
  ["bv.com","C",""],
  ["cdmsmith.com","C",""],
  ["chghealthcare.com","C",""],
  ["conduent.com","C",""],
  ["crosscountry.com","C",""],
  ["employbridge.com","C",""],
  ["exlservice.com","C",""],
  ["gftengineering.com","C",""],
  ["genpact.com","C",""],
  ["hdrinc.com","C",""],
  ["highspring.com","C",""],
  ["hubinternational.com","C",""],
  ["kellyservices.com","C",""],
  ["kimley-horn.com","C",""],
  ["kroll.com","C",""],
  ["svclnk.com","C",""],
  ["sutherlandglobal.com","C",""],
  ["trccompanies.com","C",""],
  ["ttec.com","C",""],
  ["terracon.com","C",""],
  ["baldwin.com","C",""],
  ["trueblue.com","C",""],
  ["usi.com","C",""],
  ["1800flowers.com","C",""],
  ["aloyoga.com","C",""],
  ["arhaus.com","C",""],
  ["authentic.com","C",""],
  ["beyond.com","C",""],
  ["bootbarn.com","C",""],
  ["crumblcookies.com","C",""],
  ["hims.com","C",""],
  ["knitwellgroup.com","C",""],
  ["landsend.com","C",""],
  ["lesliespool.com","C",""],
  ["nationalvision.com","C",""],
  ["ollies.com","C",""],
  ["planetfitness.com","C",""],
  ["quince.com","C",""],
  ["rei.com","C",""],
  ["revolve.com","C",""],
  ["savers.com","C",""],
  ["shoecarnival.com","C",""],
  ["shutterfly.com","C",""],
  ["sleepnumber.com","C",""],
  ["sportsmans.com","C",""],
  ["stitchfix.com","C",""],
  ["torrid.com","C",""],
  ["vuoriclothing.com","C",""],
  ["yeti.com","C",""],
  ["elfbeauty.com","C",""],
  ["ifit.com","C",""],
  ["blackbaud.com","C",""],
  ["blueyonder.com","C",""],
  ["cccis.com","C",""],
  ["dayforce.com","C",""],
  ["deel.com","C",""],
  ["finastra.com","C",""],
  ["goto.com","C",""],
  ["guidewire.com","C",""],
  ["gusto.com","C",""],
  ["jackhenry.com","C",""],
  ["kaseya.com","C",""],
  ["klaviyo.com","C",""],
  ["manh.com","C",""],
  ["paycom.com","C",""],
  ["paylocity.com","C",""],
  ["procore.com","C",""],
  ["qlik.com","C",""],
  ["realpage.com","C",""],
  ["samsara.com","C",""],
  ["smartsheet.com","C",""],
  ["solera.com","C",""],
  ["tylertech.com","C",""],
  ["ukg.com","C",""],
  ["waystar.com","C",""],
  ["yardi.com","C",""],
  ["zelis.com","C",""],
  ["zendesk.com","C",""],
  ["zetaglobal.com","C",""],
  ["zoominfo.com","C",""],
  ["athenahealth.com","C",""],
  ["americold.com","C",""],
  ["arcb.com","C",""],
  ["arrivelogistics.com","C",""],
  ["echo.com","C",""],
  ["flexport.com","C",""],
  ["kencogroup.com","C",""],
  ["modeglobal.com","C",""],
  ["penskelogistics.com","C",""],
  ["redwoodlogistics.com","C",""],
  ["werner.com","C",""],
  ["plantemoran.com","removed","$1-5B with no AI signal"],
  ["acuity.com","removed","$1-5B with no AI signal"],
  ["amerisbank.com","removed","$1-5B with no AI signal"],
  ["amica.com","removed","$1-5B with no AI signal"],
  ["atlanticunionbank.com","removed","$1-5B with no AI signal"],
  ["bokf.com","removed","$1-5B with no AI signal"],
  ["ozk.com","removed","$1-5B with no AI signal"],
  ["creditacceptance.com","removed","$1-5B with no AI signal"],
  ["crosscountrymortgage.com","removed","$1-5B with no AI signal"],
  ["emcins.com","removed","$1-5B with no AI signal"],
  ["erieinsurance.com","removed","$1-5B with no AI signal"],
  ["euronetworldwide.com","removed","$1-5B with no AI signal"],
  ["fisherinvestments.com","removed","$1-5B with no AI signal"],
  ["focuspartners.com","removed","$1-5B with no AI signal"],
  ["freedommortgage.com","removed","$1-5B with no AI signal"],
  ["grangeinsurance.com","removed","$1-5B with no AI signal"],
  ["hancockwhitney.com","removed","$1-5B with no AI signal"],
  ["horacemann.com","removed","$1-5B with no AI signal"],
  ["nelnet.com","removed","$1-5B with no AI signal"],
  ["penfed.org","removed","$1-5B with no AI signal"],
  ["prosperitybankusa.com","removed","$1-5B with no AI signal"],
  ["rlicorp.com","removed","$1-5B with no AI signal"],
  ["salliemae.com","removed","$1-5B with no AI signal"],
  ["safetyinsurance.com","removed","$1-5B with no AI signal"],
  ["schoolsfirstfcu.org","removed","$1-5B with no AI signal"],
  ["sentry.com","removed","$1-5B with no AI signal"],
  ["shift4.com","removed","$1-5B with no AI signal"],
  ["ncsecu.org","removed","$1-5B with no AI signal"],
  ["ucbi.com","removed","$1-5B with no AI signal"],
  ["thesilverlining.com","removed","$1-5B with no AI signal"],
  ["westfieldinsurance.com","removed","$1-5B with no AI signal"],
  ["westlakefinancial.com","removed","$1-5B with no AI signal"],
  ["amcon.com","removed","$1-5B with no AI signal"],
  ["benco.com","removed","$1-5B with no AI signal"],
  ["bradyplus.com","removed","$1-5B with no AI signal"],
  ["coldist.com","removed","$1-5B with no AI signal"],
  ["cesco.com","removed","$1-5B with no AI signal"],
  ["dxpe.com","removed","$1-5B with no AI signal"],
  ["dakotasupplygroup.com","removed","$1-5B with no AI signal"],
  ["distributionsolutionsgroup.com","removed","$1-5B with no AI signal"],
  ["don.com","removed","$1-5B with no AI signal"],
  ["elliottelectric.com","removed","$1-5B with no AI signal"],
  ["fwwebb.com","removed","$1-5B with no AI signal"],
  ["factorymotorparts.com","removed","$1-5B with no AI signal"],
  ["fbmsales.com","removed","$1-5B with no AI signal"],
  ["labattfood.com","removed","$1-5B with no AI signal"],
  ["lansingbp.com","removed","$1-5B with no AI signal"],
  ["liparifoods.com","removed","$1-5B with no AI signal"],
  ["lonestarelectric.com","removed","$1-5B with no AI signal"],
  ["mayerelectric.com","removed","$1-5B with no AI signal"],
  ["mc-mc.com","removed","$1-5B with no AI signal"],
  ["nexeoplastics.com","removed","$1-5B with no AI signal"],
  ["orgill.com","removed","$1-5B with no AI signal"],
  ["siglers.com","removed","$1-5B with no AI signal"],
  ["smithweb.com","removed","$1-5B with no AI signal"],
  ["sun-source.com","removed","$1-5B with no AI signal"],
  ["chefswarehouse.com","removed","$1-5B with no AI signal"],
  ["trimarkusa.com","removed","$1-5B with no AI signal"],
  ["tricorbraun.com","removed","$1-5B with no AI signal"],
  ["vallen.com","removed","$1-5B with no AI signal"],
  ["chg.com","removed","$1-5B with no AI signal"],
  ["chobani.com","removed","$1-5B with no AI signal"],
  ["daveshotchicken.com","removed","$1-5B with no AI signal"],
  ["davidsonhospitality.com","removed","$1-5B with no AI signal"],
  ["delawarenorth.com","removed","$1-5B with no AI signal"],
  ["elior-na.com","removed","$1-5B with no AI signal"],
  ["fosterfarms.com","removed","$1-5B with no AI signal"],
  ["goldencorral.com","removed","$1-5B with no AI signal"],
  ["hhmhospitality.com","removed","$1-5B with no AI signal"],
  ["highgate.com","removed","$1-5B with no AI signal"],
  ["jerseymikes.com","removed","$1-5B with no AI signal"],
  ["marcos.com","removed","$1-5B with no AI signal"],
  ["pyramidglobal.com","removed","$1-5B with no AI signal"],
  ["resers.com","removed","$1-5B with no AI signal"],
  ["risebakingcompany.com","removed","$1-5B with no AI signal"],
  ["shearers.com","removed","$1-5B with no AI signal"],
  ["sunholdings.net","removed","$1-5B with no AI signal"],
  ["tropicalsmoothiecafe.com","removed","$1-5B with no AI signal"],
  ["tropicanabrandsgroup.com","removed","$1-5B with no AI signal"],
  ["whataburger.com","removed","$1-5B with no AI signal"],
  ["winlandfoods.com","removed","$1-5B with no AI signal"],
  ["yadaventerprises.com","removed","$1-5B with no AI signal"],
  ["zaxbys.com","removed","$1-5B with no AI signal"],
  ["alamo-group.com","removed","$1-5B with no AI signal"],
  ["associatedmaterials.com","removed","$1-5B with no AI signal"],
  ["bissell.com","removed","$1-5B with no AI signal"],
  ["bridgewater-interiors.com","removed","$1-5B with no AI signal"],
  ["butterball.com","removed","$1-5B with no AI signal"],
  ["chartermfg.com","removed","$1-5B with no AI signal"],
  ["eastpennmanufacturing.com","removed","$1-5B with no AI signal"],
  ["ellwoodgroup.com","removed","$1-5B with no AI signal"],
  ["federalsignal.com","removed","$1-5B with no AI signal"],
  ["greatlakescheese.com","removed","$1-5B with no AI signal"],
  ["gbp.com","removed","$1-5B with no AI signal"],
  ["greenheck.com","removed","$1-5B with no AI signal"],
  ["haworth.com","removed","$1-5B with no AI signal"],
  ["hearthsidefoods.com","removed","$1-5B with no AI signal"],
  ["helenoftroy.com","removed","$1-5B with no AI signal"],
  ["hendrickson-intl.com","removed","$1-5B with no AI signal"],
  ["hollister.com","removed","$1-5B with no AI signal"],
  ["houseofraeford.com","removed","$1-5B with no AI signal"],
  ["intevaproducts.com","removed","$1-5B with no AI signal"],
  ["jbssinc.com","removed","$1-5B with no AI signal"],
  ["johnsonville.com","removed","$1-5B with no AI signal"],
  ["menasha.com","removed","$1-5B with no AI signal"],
  ["neapco.com","removed","$1-5B with no AI signal"],
  ["pvschemicals.com","removed","$1-5B with no AI signal"],
  ["parkdalemills.com","removed","$1-5B with no AI signal"],
  ["pistongroup.com","removed","$1-5B with no AI signal"],
  ["plastipak.com","removed","$1-5B with no AI signal"],
  ["proampac.com","removed","$1-5B with no AI signal"],
  ["quanex.com","removed","$1-5B with no AI signal"],
  ["sargento.com","removed","$1-5B with no AI signal"],
  ["trekbikes.com","removed","$1-5B with no AI signal"],
  ["usfarathane.com","removed","$1-5B with no AI signal"],
  ["taylor.com","removed","$1-5B with no AI signal"],
  ["aleragroup.com","removed","$1-5B with no AI signal"],
  ["ascensus.com","removed","$1-5B with no AI signal"],
  ["convergint.com","removed","$1-5B with no AI signal"],
  ["marcone.com","removed","$1-5B with no AI signal"],
  ["primesourcebp.com","removed","$1-5B with no AI signal"],
  ["accessionrmg.com","removed","$1-5B with no AI signal"],
  ["alliant.com","removed","$1-5B with no AI signal"],
  ["bbsi.com","removed","$1-5B with no AI signal"],
  ["beaconhillstaffing.com","removed","$1-5B with no AI signal"],
  ["broadstreetpartners.com","removed","$1-5B with no AI signal"],
  ["epicbrokers.com","removed","$1-5B with no AI signal"],
  ["expresspros.com","removed","$1-5B with no AI signal"],
  ["jacksonhealthcare.com","removed","$1-5B with no AI signal"],
  ["justworks.com","removed","$1-5B with no AI signal"],
  ["lockton.com","removed","$1-5B with no AI signal"],
  ["medicalsolutions.com","removed","$1-5B with no AI signal"],
  ["nmrk.com","removed","$1-5B with no AI signal"],
  ["onedigital.com","removed","$1-5B with no AI signal"],
  ["trinet.com","removed","$1-5B with no AI signal"],
  ["valuecityfurniture.com","removed","$1-5B with no AI signal"],
  ["ariat.com","removed","$1-5B with no AI signal"],
  ["beallsinc.com","removed","$1-5B with no AI signal"],
  ["belk.com","removed","$1-5B with no AI signal"],
  ["farmandfleet.com","removed","$1-5B with no AI signal"],
  ["mybobs.com","removed","$1-5B with no AI signal"],
  ["boscovs.com","removed","$1-5B with no AI signal"],
  ["chicos.com","removed","$1-5B with no AI signal"],
  ["fleetfarm.com","removed","$1-5B with no AI signal"],
  ["guitarcenter.com","removed","$1-5B with no AI signal"],
  ["llbean.com","removed","$1-5B with no AI signal"],
  ["livingspaces.com","removed","$1-5B with no AI signal"],
  ["mavis.com","removed","$1-5B with no AI signal"],
  ["microcenter.com","removed","$1-5B with no AI signal"],
  ["raymourflanigan.com","removed","$1-5B with no AI signal"],
  ["ruralking.com","removed","$1-5B with no AI signal"],
  ["scheels.com","removed","$1-5B with no AI signal"],
  ["sertasimmons.com","removed","$1-5B with no AI signal"],
  ["buckle.com","removed","$1-5B with no AI signal"],
  ["envestnet.com","removed","$1-5B with no AI signal"],
  ["aitworldwide.com","removed","$1-5B with no AI signal"],
  ["allenlund.com","removed","$1-5B with no AI signal"],
  ["atsinc.com","removed","$1-5B with no AI signal"],
  ["armstrongtransport.com","removed","$1-5B with no AI signal"],
  ["ascentgl.com","removed","$1-5B with no AI signal"],
  ["averitt.com","removed","$1-5B with no AI signal"],
  ["axlelogistics.com","removed","$1-5B with no AI signal"],
  ["bennettig.com","removed","$1-5B with no AI signal"],
  ["crengland.com","removed","$1-5B with no AI signal"],
  ["crst.com","removed","$1-5B with no AI signal"],
  ["capstonelogistics.com","removed","$1-5B with no AI signal"],
  ["centraltransport.com","removed","$1-5B with no AI signal"],
  ["covenantlogistics.com","removed","$1-5B with no AI signal"],
  ["cretecarrier.com","removed","$1-5B with no AI signal"],
  ["daytonfreight.com","removed","$1-5B with no AI signal"],
  ["evansdelivery.com","removed","$1-5B with no AI signal"],
  ["forwardair.com","removed","$1-5B with no AI signal"],
  ["hubgroup.com","removed","$1-5B with no AI signal"],
  ["its4logistics.com","removed","$1-5B with no AI signal"],
  ["thekag.com","removed","$1-5B with no AI signal"],
  ["landstar.com","removed","$1-5B with no AI signal"],
  ["lynden.com","removed","$1-5B with no AI signal"],
  ["nfiindustries.com","removed","$1-5B with no AI signal"],
  ["ontrac.com","removed","$1-5B with no AI signal"],
  ["pslogistics.com","removed","$1-5B with no AI signal"],
  ["pittohio.com","removed","$1-5B with no AI signal"],
  ["primeinc.com","removed","$1-5B with no AI signal"],
  ["priority1.com","removed","$1-5B with no AI signal"],
  ["rlcarriers.com","removed","$1-5B with no AI signal"],
  ["ruan.com","removed","$1-5B with no AI signal"],
  ["ryantrans.com","removed","$1-5B with no AI signal"],
  ["stgusa.com","removed","$1-5B with no AI signal"],
  ["saia.com","removed","$1-5B with no AI signal"],
  ["scotlynn.com","removed","$1-5B with no AI signal"],
  ["sekologistics.com","removed","$1-5B with no AI signal"],
  ["sefl.com","removed","$1-5B with no AI signal"],
  ["trinitylogistics.com","removed","$1-5B with no AI signal"],
  ["universallogistics.com","removed","$1-5B with no AI signal"],
  ["mercuryinsurance.com","removed","$5B+ (too large for cold outreach)"],
  ["navyfederal.org","removed","$5B+ (too large for cold outreach)"],
  ["rocketcompanies.com","removed","$5B+ (too large for cold outreach)"],
  ["accenture.com","removed","$5B+ (too large for cold outreach)"],
  ["bain.com","removed","$5B+ (too large for cold outreach)"],
  ["boozallen.com","removed","$5B+ (too large for cold outreach)"],
  ["bcg.com","removed","$5B+ (too large for cold outreach)"],
  ["deloitte.com","removed","$5B+ (too large for cold outreach)"],
  ["ey.com","removed","$5B+ (too large for cold outreach)"],
  ["gartner.com","removed","$5B+ (too large for cold outreach)"],
  ["ibm.com","removed","$5B+ (too large for cold outreach)"],
  ["kpmg.com","removed","$5B+ (too large for cold outreach)"],
  ["mckinsey.com","removed","$5B+ (too large for cold outreach)"],
  ["mercer.com","removed","$5B+ (too large for cold outreach)"],
  ["pwc.com","removed","$5B+ (too large for cold outreach)"],
  ["abcsupply.com","removed","$5B+ (too large for cold outreach)"],
  ["breakthrubev.com","removed","$5B+ (too large for cold outreach)"],
  ["fastenal.com","removed","$5B+ (too large for cold outreach)"],
  ["genpt.com","removed","$5B+ (too large for cold outreach)"],
  ["graybar.com","removed","$5B+ (too large for cold outreach)"],
  ["henryschein.com","removed","$5B+ (too large for cold outreach)"],
  ["imperialdade.com","removed","$5B+ (too large for cold outreach)"],
  ["pattersoncompanies.com","removed","$5B+ (too large for cold outreach)"],
  ["reyesbeveragegroup.com","removed","$5B+ (too large for cold outreach)"],
  ["sysco.com","removed","$5B+ (too large for cold outreach)"],
  ["usfoods.com","removed","$5B+ (too large for cold outreach)"],
  ["uslbm.com","removed","$5B+ (too large for cold outreach)"],
  ["univarsolutions.com","removed","$5B+ (too large for cold outreach)"],
  ["grainger.com","removed","$5B+ (too large for cold outreach)"],
  ["watsco.com","removed","$5B+ (too large for cold outreach)"],
  ["winsupplyinc.com","removed","$5B+ (too large for cold outreach)"],
  ["aramark.com","removed","$5B+ (too large for cold outreach)"],
  ["taylorfarms.com","removed","$5B+ (too large for cold outreach)"],
  ["caci.com","removed","$5B+ (too large for cold outreach)"],
  ["cdw.com","removed","$5B+ (too large for cold outreach)"],
  ["carahsoft.com","removed","$5B+ (too large for cold outreach)"],
  ["cognizant.com","removed","$5B+ (too large for cold outreach)"],
  ["dxc.com","removed","$5B+ (too large for cold outreach)"],
  ["insight.com","removed","$5B+ (too large for cold outreach)"],
  ["kyndryl.com","removed","$5B+ (too large for cold outreach)"],
  ["peraton.com","removed","$5B+ (too large for cold outreach)"],
  ["presidio.com","removed","$5B+ (too large for cold outreach)"],
  ["saic.com","removed","$5B+ (too large for cold outreach)"],
  ["shi.com","removed","$5B+ (too large for cold outreach)"],
  ["teksystems.com","removed","$5B+ (too large for cold outreach)"],
  ["wwt.com","removed","$5B+ (too large for cold outreach)"],
  ["cornerstonebuildingbrands.com","removed","$5B+ (too large for cold outreach)"],
  ["flex-n-gate.com","removed","$5B+ (too large for cold outreach)"],
  ["kohler.com","removed","$5B+ (too large for cold outreach)"],
  ["medline.com","removed","$5B+ (too large for cold outreach)"],
  ["novolex.com","removed","$5B+ (too large for cold outreach)"],
  ["osigroup.com","removed","$5B+ (too large for cold outreach)"],
  ["schreiberfoods.com","removed","$5B+ (too large for cold outreach)"],
  ["omnicomgroup.com","removed","$5B+ (too large for cold outreach)"],
  ["ayahealthcare.com","removed","$5B+ (too large for cold outreach)"],
  ["burnsmcd.com","removed","$5B+ (too large for cold outreach)"],
  ["cbre.com","removed","$5B+ (too large for cold outreach)"],
  ["compass.com","removed","$5B+ (too large for cold outreach)"],
  ["cushmanwakefield.com","removed","$5B+ (too large for cold outreach)"],
  ["insperity.com","removed","$5B+ (too large for cold outreach)"],
  ["jll.com","removed","$5B+ (too large for cold outreach)"],
  ["roberthalf.com","removed","$5B+ (too large for cold outreach)"],
  ["fanatics.com","removed","$5B+ (too large for cold outreach)"],
  ["newbalance.com","removed","$5B+ (too large for cold outreach)"],
  ["totalwine.com","removed","$5B+ (too large for cold outreach)"],
  ["toasttab.com","removed","$5B+ (too large for cold outreach)"],
  ["beonlogistics.com","removed","$5B+ (too large for cold outreach)"],
  ["chrobinson.com","removed","$5B+ (too large for cold outreach)"],
  ["estes-express.com","removed","$5B+ (too large for cold outreach)"],
  ["expeditors.com","removed","$5B+ (too large for cold outreach)"],
  ["gxo.com","removed","$5B+ (too large for cold outreach)"],
  ["jbhunt.com","removed","$5B+ (too large for cold outreach)"],
  ["knight-swift.com","removed","$5B+ (too large for cold outreach)"],
  ["onelineage.com","removed","$5B+ (too large for cold outreach)"],
  ["odfl.com","removed","$5B+ (too large for cold outreach)"],
  ["rxo.com","removed","$5B+ (too large for cold outreach)"],
  ["ryder.com","removed","$5B+ (too large for cold outreach)"],
  ["schneider.com","removed","$5B+ (too large for cold outreach)"],
  ["tql.com","removed","$5B+ (too large for cold outreach)"],
  ["uberfreight.com","removed","$5B+ (too large for cold outreach)"],
  ["wwex.com","removed","$5B+ (too large for cold outreach)"],
  ["magna5global.com","removed","Duplicate"],
  ["clearlake.com","removed","PE firm, not a portfolio company"],
  ["thomabravo.com","removed","PE firm, not a portfolio company"],
  ["vistaequitypartners.com","removed","PE firm, not a portfolio company"],
  ["gencap.com","removed","PE firm, not a portfolio company"],
  ["aeainvestors.com","removed","PE firm, not a portfolio company"],
  ["audaxprivateequity.com","removed","PE firm, not a portfolio company"],
  ["riversidecompany.com","removed","PE firm, not a portfolio company"],
  ["gryphon-inv.com","removed","PE firm, not a portfolio company"],
  ["hggc.com","removed","PE firm, not a portfolio company"],
  ["harvestpartners.com","removed","PE firm, not a portfolio company"],
  ["kelso.com","removed","PE firm, not a portfolio company"],
  ["kohlberg.com","removed","PE firm, not a portfolio company"],
  ["sentinelpartners.com","removed","PE firm, not a portfolio company"],
  ["shorecp.com","removed","PE firm, not a portfolio company"],
  ["bluepointcapital.com","removed","PE firm, not a portfolio company"],
  ["gridironcapital.com","removed","PE firm, not a portfolio company"],
  ["inclineequity.com","removed","PE firm, not a portfolio company"],
  ["llrpartners.com","removed","PE firm, not a portfolio company"],
  ["suncappart.com","removed","PE firm, not a portfolio company"],
  ["trivest.com","removed","PE firm, not a portfolio company"],
  ["wppartners.com","removed","PE firm, not a portfolio company"],
];
