"use client";

import { CalendarClock, Check, ChevronDown, Mail, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";

type CadenceMode="manual"|"automatic";
type CadenceChannel="email"|"linkedin_comment"|"linkedin_request"|"linkedin_message"|"intro_ask";
type CadenceStep={day:number;channel:CadenceChannel;title:string;detail:string;subject?:string;body?:string};
type Props={cardId:string;demo:boolean;channel:string;personName:string;company:string;emailVerified:boolean;subject:string;body:string;linkedinNote:string;onActivated:(message:string)=>void};

export function CadencePlanner({cardId,demo,channel,personName,company,emailVerified,subject,body,linkedinNote,onActivated}:Props){
  const [mode,setMode]=useState<CadenceMode>(emailVerified?"automatic":"manual"),[active,setActive]=useState(false),[busy,setBusy]=useState(false),[stopOnReply,setStopOnReply]=useState(true),[weekdaysOnly,setWeekdaysOnly]=useState(true);
  const steps=useMemo(()=>buildCadence({channel,personName,company,subject,body,linkedinNote}),[channel,personName,company,subject,body,linkedinNote]);
  async function activate(){
    if(active)return;
    if(demo){setActive(true);onActivated(`${mode==="automatic"?"Smart cadence activated":"Cadence saved"} in demo mode — no messages will leave the app.`);return}
    setBusy(true);
    const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC";
    const response=await fetch(`/api/cards/${cardId}/cadence`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode,stopOnReply,weekdaysOnly,sendWindow:"09:30–11:30",timeZone,steps})});
    const result=await response.json();setBusy(false);
    if(!response.ok){onActivated(result.error??"Unable to activate cadence.");return}
    setActive(true);onActivated("Cadence activated. Automatic email steps will send inside the selected window; social steps will wait for your review.");
  }
  return <section className="cadence-panel"><div className="cadence-head"><div><span className="eyebrow">Intelligent cadence</span><h3>Plan the follow-through</h3><p>Signal-aware timing with safe channel handoffs.</p></div><CalendarClock aria-hidden="true"/></div><div className="cadence-mode" aria-label="Cadence mode"><button className={mode==="manual"?"active":""} onClick={()=>setMode("manual")}><span>Review each step</span><small>Nothing advances without you</small></button><button className={mode==="automatic"?"active":""} onClick={()=>setMode("automatic")} disabled={!emailVerified}><span><Sparkles/> Smart auto</span><small>{emailVerified?"Email advances automatically":"Needs a verified email"}</small></button></div><div className="cadence-recommendation"><Sparkles/><p><strong>Recommended for this signal</strong><span>{steps.length} touches across {steps.at(-1)?.day??0} business days. Social steps stay human; email can flow automatically.</span></p></div><ol className="cadence-timeline">{steps.map((step,index)=>{const automatic=mode==="automatic"&&step.channel==="email";return <li key={`${step.day}-${step.channel}`}><div className="cadence-day"><span>{step.day===0?"TODAY":`DAY ${step.day}`}</span><i/></div><div className="cadence-step-icon">{step.channel==="email"?<Mail/>:<MessageCircle/>}</div><div className="cadence-step-copy"><div><strong>{step.title}</strong><span className={automatic?"auto-step":"review-step"}>{automatic?"AUTO":"REVIEW"}</span></div><p>{step.detail}</p>{step.body&&index>0&&<details><summary>Preview message <ChevronDown/></summary><div>{step.subject&&<b>{step.subject}</b>}<p>{step.body}</p></div></details>}</div></li>})}</ol><div className="cadence-rules"><label><input type="checkbox" checked={stopOnReply} onChange={event=>setStopOnReply(event.target.checked)}/><span><strong>Stop on any reply</strong><small>No awkward follow-up after engagement</small></span></label><label><input type="checkbox" checked={weekdaysOnly} onChange={event=>setWeekdaysOnly(event.target.checked)}/><span><strong>Business days only</strong><small>Send between 9:30–11:30 local time</small></span></label><div><ShieldCheck/><span><strong>Safety limits</strong><small>One automatic message per 3 days · sender cap enforced</small></span></div></div><button className={`activate-cadence ${active?"activated":""}`} onClick={activate} disabled={busy||active}>{active?<><Check/> Cadence active</>:<>{mode==="automatic"?"Activate smart cadence":"Save review cadence"}<span>→</span></>}</button><p className="cadence-disclosure">Automatic mode sends approved email copy only. LinkedIn and introduction steps always pause for a person.</p></section>
}

function buildCadence({channel,personName,company,subject,body,linkedinNote}:{channel:string;personName:string;company:string;subject:string;body:string;linkedinNote:string}):CadenceStep[]{
  const firstName=personName.split(" ")[0],followup=`${firstName} — sharing this once more in case the timing is useful. I can send the one-page operating pattern I mentioned; no meeting needed.`,close=`${firstName} — I’ll close the loop here. If this becomes a priority at ${company}, I’m happy to share the framework.`;
  if(channel==="email_first")return [{day:0,channel:"email",title:"Send the evidence-led email",detail:subject||"Open with the observed change",subject,body},{day:3,channel:"linkedin_request",title:"View profile and connect",detail:"Use the signal as context; do not repeat the email.",body:linkedinNote},{day:5,channel:"email",title:"Useful follow-up",detail:"Offer the asset without asking for a meeting.",subject:`Re: ${subject}`,body:followup},{day:10,channel:"email",title:"Close the loop",detail:"A short, respectful final note.",subject:`Re: ${subject}`,body:close}];
  if(channel==="intro")return [{day:0,channel:"intro_ask",title:"Request the warm introduction",detail:"Give the connector a one-sentence reason and an easy out."},{day:3,channel:"linkedin_message",title:"Send a direct note",detail:"Only if the introduction has not moved.",body:linkedinNote},{day:7,channel:"email",title:"Share the useful framework",detail:"Continue only after a warm response.",subject,body}];
  if(channel==="linkedin_only")return [{day:0,channel:"linkedin_comment",title:"Engage with the source",detail:"Add a specific observation; no pitch."},{day:1,channel:"linkedin_request",title:"Send the connection note",detail:linkedinNote},{day:5,channel:"linkedin_message",title:"Follow up after acceptance",detail:"Ask one informed question from the decision brief."}];
  return [{day:0,channel:"linkedin_comment",title:"Respond to the source",detail:"Add the drafted insight while the post is fresh."},{day:1,channel:"linkedin_request",title:"Send the connection note",detail:linkedinNote},{day:3,channel:"email",title:"Send the evidence-led email",detail:subject||"Reference the same operating question",subject,body},{day:7,channel:"email",title:"Useful follow-up",detail:"Offer the asset without adding pressure.",subject:`Re: ${subject}`,body:followup},{day:10,channel:"email",title:"Close the loop",detail:"Stop cleanly after one final note.",subject:`Re: ${subject}`,body:close}];
}
