import Link from "next/link";

type CardSummary={id:string;score:number;status:string;channel:string;why_now:string;assigned_to:string;accounts:{name:string};people:{full_name:string;title:string};signals:{type?:string;summary:string;source_url:string}};
export type DashboardData={metrics:{newSignals:number;surfacedCards:number;highPriority:number;positiveReplies:number};run:{status:string;finishedAt:string;accounts:number;signals:number;cards:number;cost:number;duration:string};sources:Array<{name:string;count:number;share:number;detail:string;filter:string}>;pipeline:Array<{name:string;count:number;note:string;href:string}>;recentSignals:Array<{id:string;type:string;account:string;summary:string;age:string;source:string;sourceUrl:string;cardId:string|null;isNew:boolean}>;accounts:Array<{name:string;signalCount:number;topSignal:string;score:number;owner:string}>;activity:Array<{time:string;label:string;detail:string}>};

export function Dashboard({data,cards,demo=false}:{data:DashboardData;cards:CardSummary[];demo?:boolean}){
  const date=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date());
  return <main className="overview">
    <section className="overview-hero"><div><div className="eyebrow">Daily intelligence overview</div><h1>{date}</h1><p>What changed across the market, who it maps to, and what deserves human attention this morning.</p></div><div className="run-summary"><div className="run-status"><span className="status-dot"/>Nightly run {data.run.status.toLowerCase()}</div><strong>{data.run.finishedAt}</strong><span>{data.run.duration} · ${data.run.cost.toFixed(2)}</span><Link href="/settings">View run controls →</Link></div></section>
    {demo&&<div className="overview-demo">Illustrative workspace · explore every view and action without connecting services</div>}
    <section className="overview-metrics"><Link href="/?view=signals" className="overview-metric"><span>New signals</span><strong>{data.metrics.newSignals}</strong><small>found in the last 48 hours</small></Link><Link href="/desk" className="overview-metric"><span>Surfaced cards</span><strong>{data.metrics.surfacedCards}</strong><small>ranked for this morning</small></Link><Link href="/desk?priority=high" className="overview-metric"><span>High priority</span><strong>{data.metrics.highPriority}</strong><small>score of 75 or above</small></Link><Link href="/desk?status=positive" className="overview-metric"><span>Positive replies</span><strong>{data.metrics.positiveReplies}</strong><small>need a human response</small></Link></section>
    <section className="overview-grid"><div className="overview-main"><div className="section-heading"><div><div className="eyebrow">Action queue</div><h2>Highest-priority cards</h2></div><Link href="/desk">Open full desk →</Link></div><div className="priority-list">{cards.slice(0,4).map((card,index)=><Link key={card.id} href={`/desk?card=${card.id}`} className="priority-row"><span className="rank">0{index+1}</span><div className="priority-person"><strong>{card.people.full_name}</strong><small>{card.people.title} · {card.accounts.name}</small></div><p>{card.why_now}</p><span className="channel-label">{card.channel.replaceAll("_"," ")}</span><span className="priority-score">{card.score}</span></Link>)}</div></div><aside className="overview-side"><div className="section-heading"><div><div className="eyebrow">Pipeline</div><h2>From signal to action</h2></div></div><div className="pipeline-list">{data.pipeline.map((stage,index)=><Link href={stage.href} className="pipeline-stage" key={stage.name}><span>{index+1}</span><div><strong>{stage.name}</strong><small>{stage.note}</small></div><b>{stage.count}</b></Link>)}</div></aside></section>
    <section className="overview-grid lower"><div className="overview-main"><div className="section-heading"><div><div className="eyebrow">Live intake</div><h2>Newest signals</h2></div><Link href="/?view=signals">See all signals →</Link></div><div className="signal-feed">{data.recentSignals.map(signal=><article className="signal-row" key={signal.id}><div>{signal.isNew&&<span className="new-label">New</span>}<span className="signal-type">{signal.type}</span><small>{signal.age}</small></div><div><strong>{signal.account}</strong><p>{signal.summary}</p></div><div className="signal-links"><a href={signal.sourceUrl} target="_blank" rel="noreferrer">{signal.source} ↗</a>{signal.cardId&&<Link href={`/desk?card=${signal.cardId}`}>Open card →</Link>}</div></article>)}</div></div><aside className="overview-side"><div className="section-heading"><div><div className="eyebrow">Source mix</div><h2>Where signals came from</h2></div></div><div className="source-list">{data.sources.map(source=><Link href={`/desk?source=${source.filter}`} key={source.name} className="source-row"><div><strong>{source.name}</strong><small>{source.detail}</small></div><b>{source.count}</b><div className="source-track"><span style={{width:`${source.share}%`}}/></div></Link>)}</div></aside></section>
    <section className="overview-grid lower"><div className="overview-main"><div className="section-heading"><div><div className="eyebrow">Account watch</div><h2>Accounts moving now</h2></div></div><table className="account-table"><thead><tr><th>Account</th><th>Signals</th><th>Strongest signal</th><th>Top score</th><th>Owner</th></tr></thead><tbody>{data.accounts.map(account=><tr key={account.name}><td><Link href="/desk">{account.name}</Link></td><td>{account.signalCount}</td><td>{account.topSignal}</td><td>{account.score}</td><td>{account.owner}</td></tr>)}</tbody></table></div><aside className="overview-side"><div className="section-heading"><div><div className="eyebrow">Human activity</div><h2>Latest decisions</h2></div></div><div className="activity-list">{data.activity.map(item=><div className="activity-row" key={`${item.time}-${item.detail}`}><time>{item.time}</time><div><strong>{item.label}</strong><small>{item.detail}</small></div></div>)}</div></aside></section>
  </main>
}
