type SignalRaw={post?:{text?:string;published?:string};job?:{title:string;days_open:number;tools_named:string[];responsibilities:string[]};announcement?:{headline?:string;excerpt?:string};event?:{name?:string;date?:string;topic?:string}};
export type InsightCard={score:number;why_now:string;channel:string;people:{full_name:string;title:string;path_score:number;connection_status:string};accounts:{name:string};signals:{type?:string;summary:string;source_url:string;observed_at?:string;raw?:SignalRaw}};

const labels:Record<string,string>={exec_post:"Executive post",job_post:"Job posting",job_cluster:"Hiring cluster",new_leader:"Leadership change",funding:"Funding event",event:"Public event",stack_change:"Technology change",other:"Market signal"};
function angle(type:string|undefined){if(type==="exec_post")return "Respond to the idea they shared, then connect it to one useful operating pattern.";if(type==="job_cluster"||type==="job_post")return "Offer the one-page JD teardown: agent work, human work, and the effect on the hire.";if(type==="new_leader")return "Acknowledge the new mandate and offer a practical first-90-days framework.";if(type==="event")return "Reference the session topic and ask one informed question—no pitch.";return "Name the change directly and offer one relevant point of view."}
function freshness(date?:string){if(!date)return "Found in the last 48 hours";return `Observed ${new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(`${date}T12:00:00`))}`}

export function SignalInsight({card}:{card:InsightCard}){
  const type=card.signals.type??undefined,label=labels[type??""]??"Signal",raw=card.signals.raw??{},linkedIn=type==="exec_post";
  const postText=raw.post?.text??card.signals.summary;
  return <section className="decision-block"><div className="decision-head"><div><div className="eyebrow">Decision brief</div><h2>Why this person, why now</h2></div><div className="decision-score"><span>Priority score</span><strong>{card.score}</strong></div></div><div className="decision-grid"><article className="source-preview"><div className="source-preview-head"><span className="source-mark">{linkedIn?"in":"NW"}</span><div><strong>{linkedIn?card.people.full_name:card.accounts.name}</strong><small>{linkedIn?`${card.people.title} · ${card.accounts.name}`:label}</small></div><span className="source-age">{freshness(card.signals.observed_at)}</span></div>{linkedIn?<blockquote>{postText}</blockquote>:type==="job_cluster"||type==="job_post"?<div className="source-content"><span className="source-kicker">{raw.job?.title??"New target-role hiring"}</span><p>{card.signals.summary}</p>{raw.job&&<div className="source-facts"><span>{raw.job.days_open} days open</span><span>{raw.job.tools_named.join(" · ")}</span><span>{raw.job.responsibilities.length} priority responsibilities</span></div>}</div>:type==="event"?<div className="source-content"><span className="source-kicker">{raw.event?.name??"Upcoming industry event"}</span><p>{raw.event?.topic??card.signals.summary}</p>{raw.event?.date&&<div className="source-facts"><span>{raw.event.date}</span></div>}</div>:<div className="source-content"><span className="source-kicker">{raw.announcement?.headline??label}</span><p>{raw.announcement?.excerpt??card.signals.summary}</p></div>}<a className="original-link" href={card.signals.source_url} target="_blank" rel="noreferrer">View original source ↗</a></article><aside className="rationale"><div className="rationale-item"><span>01</span><div><strong>Evidence of change</strong><p>{card.why_now}</p></div></div><div className="rationale-item"><span>02</span><div><strong>Likely owner</strong><p>{card.people.title} is close to the budget and operating decision.</p></div></div><div className="rationale-item"><span>03</span><div><strong>Relationship path</strong><p>{card.people.path_score>0?`${card.people.path_score}/10 path score · ${card.people.connection_status}`:"Cold path—lead with the evidence, not familiarity."}</p></div></div><div className="rationale-angle"><span>Recommended angle</span><p>{angle(type)}</p></div></aside></div></section>;
}
