import { Globe2, MessageSquare, MoreHorizontal, Repeat2, Send, ThumbsUp } from "lucide-react";

type SignalRaw={post?:{text?:string;author_name?:string;author_title?:string;published_at?:string;published?:string;reactions?:number|null;comments?:number|null;reposts?:number|null;hashtags?:string[];is_excerpt?:boolean};source?:{headline:string;publisher:string;author_name:string|null;published_at:string;excerpt:string};job?:{title:string;days_open:number;tools_named:string[];responsibilities:string[]};announcement?:{headline?:string;excerpt?:string};event?:{name?:string;date?:string;topic?:string}};
type ScoreBreakdown={signal_strength:number;person_fit:number;recency:number;relationship_path:number};
type SupportingSignal={label:string;detail:string;age:string};
export type InsightCard={
  score:number;
  score_breakdown?:ScoreBreakdown;
  why_now:string;
  brief?:string;
  channel:string;
  linkedin_note?:string|null;
  email_subject?:string|null;
  email_body?:string|null;
  supporting_signals?:SupportingSignal[];
  people:{full_name:string;title:string;path_score:number;connection_status:string};
  accounts:{name:string;domain?:string;vertical?:string;employee_range?:string};
  signals:{type?:string;summary:string;source_url:string;source_domain?:string;strength?:number;observed_at?:string;raw?:SignalRaw};
};

const labels:Record<string,string>={exec_post:"Executive post",job_post:"Job posting",job_cluster:"Hiring cluster",new_leader:"Leadership change",funding:"Funding event",event:"Public event",stack_change:"Technology change",other:"Market signal"};
function displayDate(date?:string){if(!date)return "Date unavailable";const parsed=new Date(date.length===10?`${date}T12:00:00`:date);return Number.isNaN(parsed.getTime())?date:new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(parsed)}
function freshness(date?:string){return date?`Published ${displayDate(date)}`:"Publication date unavailable"}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"N67"}
function sourceName(card:InsightCard){if(card.signals.source_domain)return card.signals.source_domain;if(card.signals.type==="exec_post")return "linkedin.com";try{return new URL(card.signals.source_url).hostname.replace(/^www\./,"")}catch{return "public source"}}
function intelligence(type:string|undefined,card:InsightCard){
  const person=card.people.full_name,company=card.accounts.name;
  if(type==="exec_post")return {pressure:"An executive has moved the topic into public view, which usually follows internal alignment or active experimentation.",fit:`${person} owns the operating workflows affected by this change and can shape budget, process, and adoption.`,timing:"The source is fresh enough to reference naturally before the conversation becomes stale.",objective:"Start a peer-level conversation around the operating decision behind the post.",question:"How are you separating routine automation from the exceptions that still need a named human owner?",caution:"Public interest does not prove an active buying process. Treat this as a relevant conversation, not declared purchase intent.",avoid:"Do not pitch a generic AI transformation or pretend the post signals budget approval."};
  if(type==="job_cluster"||type==="job_post")return {pressure:"Several related hires point to a funded capacity gap, a systems change, or both. The repeated responsibilities reveal where the workflow is straining.",fit:`${person} is likely accountable for the systems and performance outcomes behind these roles at ${company}.`,timing:"The roles are live now; outreach can help before headcount and process decisions become fixed.",objective:"Offer a useful point of view on the work design—not recruiting help or a software demo.",question:"Which parts of the new roles are truly new judgment, and which are repeatable work the existing team cannot absorb?",caution:"A hiring cluster can reflect growth rather than operational pain. Validate the mandate before framing a solution.",avoid:"Do not lead with labor replacement or imply the company should cancel its open roles."};
  if(type==="new_leader")return {pressure:"A first-time executive mandate creates a brief window when priorities, ownership, and the operating model are still being defined.",fit:`${person} is the named leader for the change and is likely building the first roadmap at ${company}.`,timing:"The appointment is recent and a warm path exists, making a concise introduction appropriate now.",objective:"Earn a short conversation by offering a practical first-90-days framework.",question:"What must be made explicit in the operating model before the modernization roadmap hardens around tools?",caution:"New leaders receive heavy outreach. Relevance and a real relationship path matter more than congratulations.",avoid:"Do not send a generic new-role message or ask for a broad discovery call."};
  if(type==="event")return {pressure:"The session topic indicates an active operating question and gives us the language the person already uses publicly.",fit:`${person} is the practitioner presenting the work, which makes them a credible owner or internal guide.`,timing:"The event is upcoming, creating a natural pre-event or same-day conversation window.",objective:"Ask one informed question that demonstrates real attention to the session topic.",question:"When support scales without another management tier, where does exception ownership live?",caution:"Speaking on a topic does not guarantee an active project. Use the event as context, not proof of demand.",avoid:"Do not hijack the event mention with a pitch or request a meeting before establishing relevance."};
  return {pressure:"The account shows a recent change that may alter priorities, budget, or operating constraints.",fit:`${person} appears close to the decision area at ${company}.`,timing:"The signal remains recent enough to create a credible reason for contact.",objective:"Validate the change and learn whether it has created an active operating priority.",question:"What changed internally as a result, and where is the team feeling the new constraint first?",caution:"The signal is directional rather than conclusive. Confirm the operating impact before offering a solution.",avoid:"Do not overstate what the public evidence proves."};
}

export function SignalInsight({card}:{card:InsightCard}){
  const type=card.signals.type??undefined,label=labels[type??""]??"Market signal",raw=card.signals.raw??{},linkedIn=type==="exec_post"&&Boolean(raw.post),intel=intelligence(type,card);
  const postText=raw.post?.text??card.signals.summary;
  const postAuthor=raw.post?.author_name??card.people.full_name,postTitle=raw.post?.author_title??card.people.title;
  const postPublished=raw.post?.published_at??raw.post?.published??card.signals.observed_at;
  const postHashtags=raw.post?.hashtags??[],hasEngagement=[raw.post?.reactions,raw.post?.comments,raw.post?.reposts].some(value=>typeof value==="number");
  const breakdown=card.score_breakdown??{signal_strength:Math.min(40,Math.round(card.score*.4)),person_fit:Math.min(30,Math.round(card.score*.3)),recency:Math.min(20,Math.round(card.score*.2)),relationship_path:Math.min(10,card.people.path_score)};
  const supporting=card.supporting_signals??[{label,detail:card.signals.summary,age:freshness(card.signals.observed_at)}];
  return <section className="decision-block intelligence-dossier">
    <div className="decision-head"><div><div className="eyebrow">Complete decision dossier</div><h2>Why this person, why now</h2></div><a className="decision-score score-link" href="#score-anatomy" aria-label={`View the ${card.score} point score breakdown`}><span>Priority score</span><strong>{card.score}</strong><small>View breakdown ↓</small></a></div>
    <div className="verdict-strip"><div><span>Primary trigger</span><strong>{label}</strong></div><div><span>Signal strength</span><strong>{card.signals.strength??breakdown.signal_strength} / 40</strong></div><div><span>Best channel</span><strong>{card.channel.replaceAll("_"," ")}</strong></div><div><span>Published</span><strong>{displayDate(postPublished??raw.source?.published_at??card.signals.observed_at)}</strong></div></div>

    <div className="decision-grid">
      <article className={`source-preview ${linkedIn?"linkedin-source":""}`}>
        <div className="source-label"><span>{linkedIn?"Actual LinkedIn post":"Actual public source"}</span><b>Source-backed evidence</b></div>
        {linkedIn&&raw.post?<div className="linkedin-post">
          <div className="linkedin-header"><div className="linkedin-avatar linkedin-initials">{initials(postAuthor)}</div><div><strong>{postAuthor}</strong><p>{postTitle} at {card.accounts.name}</p><small>{displayDate(postPublished)} · <Globe2 size={11} strokeWidth={2}/></small></div><MoreHorizontal className="linkedin-more" size={22} strokeWidth={2.2} aria-hidden="true"/></div>
          <div className="linkedin-body"><p>{postText}</p>{raw.post.is_excerpt&&<small className="excerpt-label">Verified excerpt — open the original for the complete post.</small>}{postHashtags.length>0&&<span className="linkedin-tags">{postHashtags.join(" ")}</span>}</div>
          <div className="linkedin-engagement">{hasEngagement?<><span>{typeof raw.post.reactions==="number"?`${raw.post.reactions} reactions`:"Reactions unavailable"}</span><span>{typeof raw.post.comments==="number"?`${raw.post.comments} comments`:"Comments unavailable"}{typeof raw.post.reposts==="number"?` · ${raw.post.reposts} reposts`:""}</span></>:<span>Engagement metrics were not visible in the public source.</span>}</div>
          <div className="linkedin-actions" aria-label="LinkedIn post actions"><span><ThumbsUp/>Like</span><span><MessageSquare/>Comment</span><span><Repeat2/>Repost</span><span><Send/>Send</span></div>
        </div>:<><div className="source-preview-head"><span className="source-mark">N67</span><div><strong>{raw.source?.publisher??card.accounts.name}</strong><small>{raw.source?.author_name?`By ${raw.source.author_name}`:sourceName(card)}</small></div><span className="source-age">{freshness(raw.source?.published_at??card.signals.observed_at)}</span></div>{type==="job_cluster"||type==="job_post"?<div className="source-content"><span className="source-kicker">{raw.job?.title??raw.source?.headline??"New target-role hiring"}</span><p>{raw.source?.excerpt??card.signals.summary}</p>{raw.job&&<><div className="source-facts"><span>{raw.job.days_open} days open</span>{raw.job.tools_named.map(tool=><span key={tool}>{tool}</span>)}</div><ul className="evidence-list">{raw.job.responsibilities.map(item=><li key={item}>{item}</li>)}</ul></>}</div>:type==="event"?<div className="source-content"><span className="source-kicker">{raw.event?.name??raw.source?.headline??"Industry event"}</span><p>{raw.event?.topic??raw.source?.excerpt??card.signals.summary}</p>{raw.event?.date&&<div className="source-facts"><span>{raw.event.date}</span></div>}</div>:<div className="source-content"><span className="source-kicker">{raw.source?.headline??raw.announcement?.headline??label}</span><p>{raw.source?.excerpt??raw.announcement?.excerpt??card.signals.summary}</p></div>}</>}
        <div className="source-proof"><span>SOURCE / {sourceName(card).toUpperCase()}</span><span>{freshness(postPublished??raw.source?.published_at??card.signals.observed_at).toUpperCase()}</span></div>
        <a className="original-link" href={card.signals.source_url} target="_blank" rel="noreferrer">Open the actual source ↗</a>
      </article>
      <aside className="rationale"><div className="recommendation-chip"><span>Recommended</span><strong>Reach out today</strong></div><div className="rationale-intro"><span>The short answer</span><p>{card.why_now}</p></div><div className="rationale-item"><span>01</span><div><strong>What changed</strong><p>{intel.pressure}</p></div></div><div className="rationale-item"><span>02</span><div><strong>Why {card.people.full_name.split(" ")[0]}</strong><p>{intel.fit}</p></div></div><div className="rationale-item"><span>03</span><div><strong>Why now</strong><p>{intel.timing}</p></div></div>{(card.linkedin_note||card.email_body)&&<div className="quick-outreach"><span>MESSAGE READY</span>{card.linkedin_note&&<div><b>LinkedIn</b><p>{card.linkedin_note}</p></div>}{card.email_body&&<div><b>Email · {card.email_subject}</b><p>{card.email_body}</p></div>}<a href="#outreach-message">Open and edit both messages ↓</a></div>}<a className="rationale-jump" href="#recommended-move">See the recommended move ↓</a></aside>
    </div>

    <div className="intel-detail-grid"><div className="intel-main"><section className="intel-section"><div className="intel-section-head"><span>01 / Evidence stack</span><h3>Signals supporting the decision</h3><small>{supporting.length} public observations</small></div><div className="supporting-signals">{supporting.map((signal,index)=><article key={`${signal.label}-${index}`}><span>0{index+1}</span><div><strong>{signal.label}</strong><p>{signal.detail}</p></div><time>{signal.age}</time></article>)}</div></section><section className="intel-section"><div className="intel-section-head"><span>02 / Conversation thesis</span><h3>What to learn—not what to pitch</h3></div><div className="thesis-block"><span>WORKING HYPOTHESIS</span><p>{intel.objective}</p><span>BEST DISCOVERY QUESTION</span><blockquote>“{intel.question}”</blockquote></div></section></div>
      <aside className="intel-sidebar"><section className="intel-section score-anatomy-section" id="score-anatomy"><div className="intel-section-head compact"><span>Score anatomy / {card.score} points</span><h3>Confidence by factor</h3></div><div className="score-anatomy"><ScoreRow label="Signal strength" value={breakdown.signal_strength} max={40}/><ScoreRow label="Person fit" value={breakdown.person_fit} max={30}/><ScoreRow label="Recency" value={breakdown.recency} max={20}/><ScoreRow label="Relationship path" value={breakdown.relationship_path} max={10}/></div></section><section className="intel-section account-context"><div className="intel-section-head compact"><span>Account record</span><h3>{card.accounts.name}</h3></div><dl><div><dt>Domain</dt><dd>{card.accounts.domain??"Not recorded"}</dd></div><div><dt>Category</dt><dd>{card.accounts.vertical??"Target account"}</dd></div><div><dt>Company size</dt><dd>{card.accounts.employee_range??"Not recorded"}</dd></div><div><dt>Signal owner</dt><dd>{card.people.title}</dd></div></dl></section></aside></div>

    <section className="recommended-move" id="recommended-move"><div className="move-heading"><span>03 / Recommended move</span><h3>A specific next action</h3></div><div className="move-grid"><div><span>CHANNEL</span><strong>{card.channel.replaceAll("_"," ")}</strong><p>Use the public evidence as context and keep the first touch low-friction.</p></div><div><span>OBJECTIVE</span><strong>Validate the operating priority</strong><p>{intel.objective}</p></div><div><span>WATCH-OUT</span><strong>Do not overread the signal</strong><p>{intel.caution}</p></div><div><span>AVOID</span><strong>Protect credibility</strong><p>{intel.avoid}</p></div></div></section>
    <div className="verification-strip"><span><i/> PUBLIC SOURCE VERIFIED</span><span><i/> PERSON-ROLE MATCH REVIEWED</span><span><i/> OUTREACH REQUIRES HUMAN APPROVAL</span></div>
  </section>;
}

function ScoreRow({label,value,max}:{label:string;value:number;max:number}){return <div className="score-row"><div><span>{label}</span><strong>{value}/{max}</strong></div><div className="score-track"><span style={{width:`${Math.min(100,value/max*100)}%`}}/></div></div>}
