create extension if not exists pgcrypto;
create type account_status as enum ('active','paused','client','do_not_contact');
create type person_level as enum ('owner','influencer','adjacent','unknown');
create type email_status as enum ('verified','unverified','catch_all','none');
create type connection_status as enum ('none','requested','connected');
create type signal_type as enum ('job_post','job_cluster','exec_post','new_leader','funding','event','stack_change','other');
create type card_channel as enum ('linkedin_first','email_first','intro','linkedin_only');
create type card_status as enum ('new','approved','edited','snoozed','dismissed','sent','replied','positive','meeting','archived');
create type touch_channel as enum ('linkedin_comment','linkedin_request','linkedin_message','email','intro_ask');
create type reply_classification as enum ('positive','neutral','objection','referral','ooo','negative','none');
create type app_owner as enum ('josh','jenna');

create table accounts(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),name text not null,domain text not null unique,vertical text,employee_range text,hq_city text,hq_state text,target_titles text[] not null default '{}',linkedin_url text,careers_url text,news_query text,status account_status not null default 'active',last_scouted_at timestamptz,email_pattern text,pattern_confidence numeric);
create table people(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),account_id uuid not null references accounts on delete cascade,full_name text not null,first_name text not null,last_name text not null,title text not null,level person_level not null default 'unknown',linkedin_url text,email text,email_status email_status not null default 'none',email_source text,email_verified_at timestamptz,connection_status connection_status not null default 'none',connection_owner app_owner,path_score int not null default 0 check(path_score between 0 and 10),do_not_contact boolean not null default false);
create unique index people_linkedin_unique on people(linkedin_url) where linkedin_url is not null;
create unique index people_name_account_unique on people(account_id,lower(full_name));
create table signals(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),account_id uuid not null references accounts on delete cascade,person_id uuid references people on delete set null,type signal_type not null,summary text not null,source_url text not null,source_domain text,observed_at date not null,found_at timestamptz not null default now(),raw jsonb not null default '{}',hash text not null,strength int not null default 0 check(strength between 0 and 40),modifiers jsonb not null default '{}',unique(account_id,hash));
create table cards(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),signal_id uuid not null references signals on delete cascade,person_id uuid not null references people on delete cascade,account_id uuid not null references accounts on delete cascade,score int not null,score_breakdown jsonb not null default '{}',brief text not null,email_subject text,email_body text,why_now text not null,channel card_channel not null,linkedin_comment text,linkedin_note text,status card_status not null default 'new',dismiss_reason text,snooze_until date,assigned_to app_owner not null,surfaced_on date,unique(signal_id,person_id));
create table touches(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),card_id uuid not null references cards on delete cascade,person_id uuid not null references people on delete cascade,channel touch_channel not null,sent_at timestamptz,sent_by app_owner not null,gmail_thread_id text,body text,reply_at timestamptz,reply_classification reply_classification not null default 'none');
create table runs(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),started_at timestamptz not null default now(),finished_at timestamptz,accounts_scouted int not null default 0,signals_new int not null default 0,cards_created int not null default 0,cost_usd numeric not null default 0,errors jsonb not null default '[]');
create table gmail_connections(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),owner app_owner not null unique,email text not null,refresh_token_ciphertext text not null,history_id text);
create table team_connections(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),owner app_owner not null,linkedin_url text,full_name text not null,company text,title text);
create table job_title_rules(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),vertical text not null,pattern text not null,department text not null,active boolean not null default true);

create or replace function set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
do $$ declare t text; begin foreach t in array array['accounts','people','signals','cards','touches','runs','gmail_connections'] loop execute format('create trigger %I_updated before update on %I for each row execute function set_updated_at()',t,t); end loop; end $$;
alter table accounts enable row level security;alter table people enable row level security;alter table signals enable row level security;alter table cards enable row level security;alter table touches enable row level security;alter table runs enable row level security;alter table team_connections enable row level security;alter table job_title_rules enable row level security;
do $$ declare t text; begin foreach t in array array['accounts','people','signals','cards','touches','runs','team_connections','job_title_rules'] loop execute format('create policy authenticated_all on %I for all to authenticated using (true) with check (true)',t); end loop; end $$;
create index cards_queue on cards(status,surfaced_on,score desc);create index signals_recent on signals(account_id,observed_at desc);create index touches_thread on touches(gmail_thread_id) where gmail_thread_id is not null;
